-- ECE Type Review — Supabase schema + migration
-- Safe to run on a fresh project or over the previous ECE Type Review schema.
-- Run the ENTIRE file in Supabase SQL Editor after uploading this build.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_length check (char_length(username) between 3 and 32),
  constraint profiles_username_format check (username ~ '^[A-Za-z0-9_][A-Za-z0-9_.-]*$')
);
create unique index if not exists profiles_username_lower_uidx on public.profiles(lower(username));

create table if not exists public.banks (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  subject text not null default '',
  description text not null default '',
  visibility text not null default 'public',
  bank_type text not null default 'typelearning',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint banks_name_length check (char_length(name) between 1 and 120),
  constraint banks_subject_length check (char_length(subject) <= 120),
  constraint banks_description_length check (char_length(description) <= 1000),
  constraint banks_visibility_check check (visibility in ('public','private')),
  constraint banks_bank_type_check check (bank_type in ('typelearning','multiple_choice'))
);

-- Migration from the previous schema: old banks become TypeLearning automatically.
alter table public.banks add column if not exists bank_type text not null default 'typelearning';
alter table public.banks drop constraint if exists banks_bank_type_check;
alter table public.banks add constraint banks_bank_type_check check (bank_type in ('typelearning','multiple_choice'));
create index if not exists banks_owner_id_idx on public.banks(owner_id);
create index if not exists banks_visibility_updated_idx on public.banks(visibility,updated_at desc);
create index if not exists banks_name_lower_idx on public.banks(lower(name));
create index if not exists banks_subject_lower_idx on public.banks(lower(subject));
create index if not exists banks_type_visibility_idx on public.banks(bank_type,visibility,updated_at desc);

create table if not exists public.bank_entries (
  id bigint generated by default as identity primary key,
  bank_id uuid not null references public.banks(id) on delete cascade,
  position integer not null default 0,
  term text,
  definition text,
  question text,
  choices jsonb,
  correct_index integer,
  explanation text not null default '',
  created_at timestamptz not null default now()
);

-- Migration from the previous TypeLearning-only entry table.
alter table public.bank_entries alter column term drop not null;
alter table public.bank_entries alter column definition drop not null;
alter table public.bank_entries add column if not exists question text;
alter table public.bank_entries add column if not exists choices jsonb;
alter table public.bank_entries add column if not exists correct_index integer;
alter table public.bank_entries add column if not exists explanation text not null default '';
alter table public.bank_entries drop constraint if exists bank_entries_term_nonempty;
alter table public.bank_entries drop constraint if exists bank_entries_definition_nonempty;
create index if not exists bank_entries_bank_id_idx on public.bank_entries(bank_id);
create unique index if not exists bank_entries_bank_position_uidx on public.bank_entries(bank_id,position);

create table if not exists public.user_bank_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  bank_id uuid not null references public.banks(id) on delete cascade,
  entry_fingerprint text not null,
  encounter_count integer not null default 0,
  correct_count integer not null default 0,
  incorrect_count integer not null default 0,
  revealed_count integer not null default 0,
  last_encountered_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key(user_id,bank_id,entry_fingerprint),
  constraint progress_counts_nonnegative check (encounter_count >= 0 and correct_count >= 0 and incorrect_count >= 0 and revealed_count >= 0),
  constraint progress_fingerprint_nonempty check (length(trim(entry_fingerprint)) > 0)
);
create index if not exists user_bank_progress_bank_idx on public.user_bank_progress(bank_id,user_id);


create table if not exists public.user_bank_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  bank_id uuid not null references public.banks(id) on delete cascade,
  coverage_reset_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key(user_id,bank_id)
);
create index if not exists user_bank_state_bank_idx on public.user_bank_state(bank_id,user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists banks_set_updated_at on public.banks;
create trigger banks_set_updated_at before update on public.banks for each row execute function public.set_updated_at();
drop trigger if exists progress_set_updated_at on public.user_bank_progress;
create trigger progress_set_updated_at before update on public.user_bank_progress for each row execute function public.set_updated_at();
drop trigger if exists bank_state_set_updated_at on public.user_bank_state;
create trigger bank_state_set_updated_at before update on public.user_bank_state for each row execute function public.set_updated_at();

-- Enforce entry shape according to the parent bank type.
create or replace function public.validate_bank_entry()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  parent_type text;
  choice_count integer;
  blank_choice_count integer;
begin
  select b.bank_type into parent_type from public.banks b where b.id = new.bank_id;
  if parent_type is null then raise exception 'Parent bank does not exist'; end if;

  if parent_type = 'typelearning' then
    if length(trim(coalesce(new.term,''))) = 0 or length(trim(coalesce(new.definition,''))) = 0 then
      raise exception 'TypeLearning entries require non-empty term and definition';
    end if;
    new.question := null;
    new.choices := null;
    new.correct_index := null;
    new.explanation := '';
  elsif parent_type = 'multiple_choice' then
    if length(trim(coalesce(new.question,''))) = 0 then raise exception 'MCQ entries require question text'; end if;
    if new.choices is null or jsonb_typeof(new.choices) <> 'array' then raise exception 'MCQ choices must be a JSON array'; end if;
    choice_count := jsonb_array_length(new.choices);
    if choice_count < 2 or choice_count > 6 then raise exception 'MCQ entries require 2 to 6 choices'; end if;
    select count(*) into blank_choice_count from jsonb_array_elements_text(new.choices) c(value) where length(trim(c.value)) = 0;
    if blank_choice_count > 0 then raise exception 'MCQ choices cannot be blank'; end if;
    if new.correct_index is null or new.correct_index < 0 or new.correct_index >= choice_count then raise exception 'MCQ correct_index is out of range'; end if;
    new.term := null;
    new.definition := null;
    new.explanation := coalesce(new.explanation,'');
  else
    raise exception 'Unsupported bank type: %', parent_type;
  end if;
  return new;
end;
$$;

drop trigger if exists bank_entries_validate on public.bank_entries;
create trigger bank_entries_validate before insert or update on public.bank_entries for each row execute function public.validate_bank_entry();

create schema if not exists private;
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare requested text; candidate text;
begin
  requested := coalesce(nullif(trim(new.raw_user_meta_data ->> 'username'),''),split_part(coalesce(new.email,''),'@',1),'user');
  candidate := lower(regexp_replace(requested,'[^A-Za-z0-9_.-]+','','g'));
  if char_length(candidate) < 3 then candidate := 'user_' || substr(new.id::text,1,6); end if;
  candidate := left(candidate,32);
  if exists(select 1 from public.profiles p where lower(p.username)=lower(candidate)) then candidate := left(candidate,24) || '_' || substr(new.id::text,1,6); end if;
  insert into public.profiles(id,username) values(new.id,candidate) on conflict(id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();

alter table public.profiles enable row level security;
alter table public.banks enable row level security;
alter table public.bank_entries enable row level security;
alter table public.user_bank_progress enable row level security;
alter table public.user_bank_state enable row level security;

revoke all on table public.profiles from anon,authenticated;
revoke all on table public.banks from anon,authenticated;
revoke all on table public.bank_entries from anon,authenticated;
revoke all on table public.user_bank_progress from anon,authenticated;
revoke all on table public.user_bank_state from anon,authenticated;
grant select on table public.profiles to anon,authenticated;
grant update on table public.profiles to authenticated;
grant select on table public.banks to anon,authenticated;
grant insert,update,delete on table public.banks to authenticated;
grant select on table public.bank_entries to anon,authenticated;
grant insert,update,delete on table public.bank_entries to authenticated;
grant select,insert,update,delete on table public.user_bank_progress to authenticated;
grant select,insert,update,delete on table public.user_bank_state to authenticated;
grant usage,select on sequence public.bank_entries_id_seq to authenticated;

drop policy if exists "profiles are publicly readable" on public.profiles;
create policy "profiles are publicly readable" on public.profiles for select to anon,authenticated using(true);
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);

drop policy if exists "public banks readable or owner readable" on public.banks;
create policy "public banks readable or owner readable" on public.banks for select to anon,authenticated using(visibility='public' or owner_id=(select auth.uid()));
drop policy if exists "users create own banks" on public.banks;
create policy "users create own banks" on public.banks for insert to authenticated with check(owner_id=(select auth.uid()));
drop policy if exists "owners update banks" on public.banks;
create policy "owners update banks" on public.banks for update to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
drop policy if exists "owners delete banks" on public.banks;
create policy "owners delete banks" on public.banks for delete to authenticated using(owner_id=(select auth.uid()));

drop policy if exists "public bank entries readable or owner readable" on public.bank_entries;
create policy "public bank entries readable or owner readable" on public.bank_entries for select to anon,authenticated using(exists(select 1 from public.banks b where b.id=bank_entries.bank_id and (b.visibility='public' or b.owner_id=(select auth.uid()))));
drop policy if exists "owners insert bank entries" on public.bank_entries;
create policy "owners insert bank entries" on public.bank_entries for insert to authenticated with check(exists(select 1 from public.banks b where b.id=bank_entries.bank_id and b.owner_id=(select auth.uid())));
drop policy if exists "owners update bank entries" on public.bank_entries;
create policy "owners update bank entries" on public.bank_entries for update to authenticated using(exists(select 1 from public.banks b where b.id=bank_entries.bank_id and b.owner_id=(select auth.uid()))) with check(exists(select 1 from public.banks b where b.id=bank_entries.bank_id and b.owner_id=(select auth.uid())));
drop policy if exists "owners delete bank entries" on public.bank_entries;
create policy "owners delete bank entries" on public.bank_entries for delete to authenticated using(exists(select 1 from public.banks b where b.id=bank_entries.bank_id and b.owner_id=(select auth.uid())));

drop policy if exists "users read own progress" on public.user_bank_progress;
create policy "users read own progress" on public.user_bank_progress for select to authenticated using(user_id=(select auth.uid()));
drop policy if exists "users insert own progress" on public.user_bank_progress;
create policy "users insert own progress" on public.user_bank_progress for insert to authenticated with check(user_id=(select auth.uid()) and exists(select 1 from public.banks b where b.id=user_bank_progress.bank_id and (b.visibility='public' or b.owner_id=(select auth.uid()))));
drop policy if exists "users update own progress" on public.user_bank_progress;
create policy "users update own progress" on public.user_bank_progress for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
drop policy if exists "users delete own progress" on public.user_bank_progress;
create policy "users delete own progress" on public.user_bank_progress for delete to authenticated using(user_id=(select auth.uid()));


drop policy if exists "users read own bank state" on public.user_bank_state;
create policy "users read own bank state" on public.user_bank_state for select to authenticated using(user_id=(select auth.uid()));
drop policy if exists "users insert own bank state" on public.user_bank_state;
create policy "users insert own bank state" on public.user_bank_state for insert to authenticated with check(user_id=(select auth.uid()) and exists(select 1 from public.banks b where b.id=user_bank_state.bank_id and (b.visibility='public' or b.owner_id=(select auth.uid()))));
drop policy if exists "users update own bank state" on public.user_bank_state;
create policy "users update own bank state" on public.user_bank_state for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
drop policy if exists "users delete own bank state" on public.user_bank_state;
create policy "users delete own bank state" on public.user_bank_state for delete to authenticated using(user_id=(select auth.uid()));

-- Atomic progress increment. Security invoker means RLS still applies.
create or replace function public.record_bank_progress(
  p_bank_id uuid,
  p_entry_fingerprint text,
  p_encounter_delta integer default 0,
  p_correct_delta integer default 0,
  p_incorrect_delta integer default 0,
  p_revealed_delta integer default 0,
  p_last_encountered_at timestamptz default null
)
returns void language plpgsql security invoker set search_path='' as $$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  insert into public.user_bank_progress(user_id,bank_id,entry_fingerprint,encounter_count,correct_count,incorrect_count,revealed_count,last_encountered_at)
  values(auth.uid(),p_bank_id,p_entry_fingerprint,greatest(p_encounter_delta,0),greatest(p_correct_delta,0),greatest(p_incorrect_delta,0),greatest(p_revealed_delta,0),p_last_encountered_at)
  on conflict(user_id,bank_id,entry_fingerprint) do update set
    encounter_count=public.user_bank_progress.encounter_count+greatest(excluded.encounter_count,0),
    correct_count=public.user_bank_progress.correct_count+greatest(excluded.correct_count,0),
    incorrect_count=public.user_bank_progress.incorrect_count+greatest(excluded.incorrect_count,0),
    revealed_count=public.user_bank_progress.revealed_count+greatest(excluded.revealed_count,0),
    last_encountered_at=coalesce(excluded.last_encountered_at,public.user_bank_progress.last_encountered_at);
end;
$$;

create or replace function public.reset_bank_coverage(p_bank_id uuid,p_reset_at timestamptz default now())
returns void language sql security invoker set search_path='' as $$
  insert into public.user_bank_state(user_id,bank_id,coverage_reset_at)
  values(auth.uid(),p_bank_id,p_reset_at)
  on conflict(user_id,bank_id) do update set coverage_reset_at=excluded.coverage_reset_at;
$$;

create or replace function public.merge_bank_state(p_bank_id uuid,p_coverage_reset_at timestamptz)
returns void language sql security invoker set search_path='' as $$
  insert into public.user_bank_state(user_id,bank_id,coverage_reset_at)
  values(auth.uid(),p_bank_id,p_coverage_reset_at)
  on conflict(user_id,bank_id) do update set
    coverage_reset_at=greatest(public.user_bank_state.coverage_reset_at,excluded.coverage_reset_at);
$$;

create or replace function public.merge_bank_progress_batch(p_bank_id uuid,p_records jsonb)
returns void language plpgsql security invoker set search_path='' as $$
declare item jsonb;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  for item in select elem from jsonb_array_elements(coalesce(p_records,'[]'::jsonb)) as t(elem) loop
    insert into public.user_bank_progress(user_id,bank_id,entry_fingerprint,encounter_count,correct_count,incorrect_count,revealed_count,last_encountered_at)
    values(auth.uid(),p_bank_id,item->>'entry_fingerprint',greatest(coalesce((item->>'encounter_count')::integer,0),0),greatest(coalesce((item->>'correct_count')::integer,0),0),greatest(coalesce((item->>'incorrect_count')::integer,0),0),greatest(coalesce((item->>'revealed_count')::integer,0),0),nullif(item->>'last_encountered_at','')::timestamptz)
    on conflict(user_id,bank_id,entry_fingerprint) do update set
      encounter_count=greatest(public.user_bank_progress.encounter_count,excluded.encounter_count),
      correct_count=greatest(public.user_bank_progress.correct_count,excluded.correct_count),
      incorrect_count=greatest(public.user_bank_progress.incorrect_count,excluded.incorrect_count),
      revealed_count=greatest(public.user_bank_progress.revealed_count,excluded.revealed_count),
      last_encountered_at=greatest(public.user_bank_progress.last_encountered_at,excluded.last_encountered_at);
  end loop;
end;
$$;

grant execute on function public.record_bank_progress(uuid,text,integer,integer,integer,integer,timestamptz) to authenticated;
grant execute on function public.reset_bank_coverage(uuid,timestamptz) to authenticated;
grant execute on function public.merge_bank_state(uuid,timestamptz) to authenticated;
grant execute on function public.merge_bank_progress_batch(uuid,jsonb) to authenticated;

-- Return type changed from the previous build, so drop then recreate.
drop function if exists public.search_public_banks(text,integer);
drop function if exists public.search_public_banks(text,text,integer);
create function public.search_public_banks(search_term text default '',bank_type_filter text default '',limit_count integer default 50)
returns table(
  id uuid,
  name text,
  subject text,
  description text,
  bank_type text,
  uploader_username text,
  entry_count bigint,
  created_at timestamptz,
  updated_at timestamptz
)
language sql stable set search_path='' as $$
  select b.id,b.name,b.subject,b.description,b.bank_type,p.username,count(e.id)::bigint,b.created_at,b.updated_at
  from public.banks b
  join public.profiles p on p.id=b.owner_id
  left join public.bank_entries e on e.bank_id=b.id
  where b.visibility='public'
    and (coalesce(trim(bank_type_filter),'')='' or b.bank_type=trim(bank_type_filter))
    and (
      coalesce(trim(search_term),'')=''
      or b.name ilike '%'||trim(search_term)||'%'
      or b.subject ilike '%'||trim(search_term)||'%'
      or b.description ilike '%'||trim(search_term)||'%'
      or p.username ilike '%'||trim(search_term)||'%'
      or exists(
        select 1 from public.bank_entries se where se.bank_id=b.id and (
          coalesce(se.term,'') ilike '%'||trim(search_term)||'%'
          or coalesce(se.definition,'') ilike '%'||trim(search_term)||'%'
          or coalesce(se.question,'') ilike '%'||trim(search_term)||'%'
          or coalesce(se.explanation,'') ilike '%'||trim(search_term)||'%'
          or coalesce(se.choices::text,'') ilike '%'||trim(search_term)||'%'
        )
      )
    )
  group by b.id,p.username
  order by b.updated_at desc
  limit least(greatest(coalesce(limit_count,50),1),100);
$$;
grant execute on function public.search_public_banks(text,text,integer) to anon,authenticated;
