-- ECE Type Review cloud schema for Supabase
-- Run this entire file once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_length check (char_length(username) between 3 and 32),
  constraint profiles_username_format check (username ~ '^[A-Za-z0-9_][A-Za-z0-9_.-]*$')
);
create unique index if not exists profiles_username_lower_uidx on public.profiles (lower(username));

create table if not exists public.banks (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  subject text not null default '',
  description text not null default '',
  visibility text not null default 'public',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint banks_name_length check (char_length(name) between 1 and 120),
  constraint banks_subject_length check (char_length(subject) <= 120),
  constraint banks_description_length check (char_length(description) <= 1000),
  constraint banks_visibility_check check (visibility in ('public','private'))
);
create index if not exists banks_owner_id_idx on public.banks(owner_id);
create index if not exists banks_visibility_updated_idx on public.banks(visibility, updated_at desc);
create index if not exists banks_name_lower_idx on public.banks(lower(name));
create index if not exists banks_subject_lower_idx on public.banks(lower(subject));

create table if not exists public.bank_entries (
  id bigint generated by default as identity primary key,
  bank_id uuid not null references public.banks(id) on delete cascade,
  position integer not null default 0,
  term text not null,
  definition text not null,
  created_at timestamptz not null default now(),
  constraint bank_entries_term_nonempty check (length(trim(term)) > 0),
  constraint bank_entries_definition_nonempty check (length(trim(definition)) > 0)
);
create index if not exists bank_entries_bank_id_idx on public.bank_entries(bank_id);
create unique index if not exists bank_entries_bank_position_uidx on public.bank_entries(bank_id, position);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists banks_set_updated_at on public.banks;
create trigger banks_set_updated_at
before update on public.banks
for each row execute function public.set_updated_at();

create schema if not exists private;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested text;
  candidate text;
begin
  requested := coalesce(nullif(trim(new.raw_user_meta_data ->> 'username'), ''), split_part(coalesce(new.email, ''), '@', 1), 'user');
  candidate := lower(regexp_replace(requested, '[^A-Za-z0-9_.-]+', '', 'g'));
  if char_length(candidate) < 3 then candidate := 'user_' || substr(new.id::text, 1, 6); end if;
  candidate := left(candidate, 32);
  if exists (select 1 from public.profiles p where lower(p.username) = lower(candidate)) then
    candidate := left(candidate, 24) || '_' || substr(new.id::text, 1, 6);
  end if;
  insert into public.profiles(id, username) values (new.id, candidate)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

alter table public.profiles enable row level security;
alter table public.banks enable row level security;
alter table public.bank_entries enable row level security;

-- Explicit grants. Policies below still determine which rows are visible or mutable.
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.banks from anon, authenticated;
revoke all on table public.bank_entries from anon, authenticated;

grant select on table public.profiles to anon, authenticated;
grant update on table public.profiles to authenticated;
grant select on table public.banks to anon, authenticated;
grant insert, update, delete on table public.banks to authenticated;
grant select on table public.bank_entries to anon, authenticated;
grant insert, update, delete on table public.bank_entries to authenticated;
grant usage, select on sequence public.bank_entries_id_seq to authenticated;

drop policy if exists "profiles are publicly readable" on public.profiles;
create policy "profiles are publicly readable"
on public.profiles for select
to anon, authenticated
using (true);

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "public banks readable or owner readable" on public.banks;
create policy "public banks readable or owner readable"
on public.banks for select
to anon, authenticated
using (visibility = 'public' or owner_id = (select auth.uid()));

drop policy if exists "users create own banks" on public.banks;
create policy "users create own banks"
on public.banks for insert
to authenticated
with check (owner_id = (select auth.uid()));

drop policy if exists "owners update banks" on public.banks;
create policy "owners update banks"
on public.banks for update
to authenticated
using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));

drop policy if exists "owners delete banks" on public.banks;
create policy "owners delete banks"
on public.banks for delete
to authenticated
using (owner_id = (select auth.uid()));

drop policy if exists "public bank entries readable or owner readable" on public.bank_entries;
create policy "public bank entries readable or owner readable"
on public.bank_entries for select
to anon, authenticated
using (
  exists (
    select 1 from public.banks b
    where b.id = bank_entries.bank_id
      and (b.visibility = 'public' or b.owner_id = (select auth.uid()))
  )
);

drop policy if exists "owners insert bank entries" on public.bank_entries;
create policy "owners insert bank entries"
on public.bank_entries for insert
to authenticated
with check (
  exists (
    select 1 from public.banks b
    where b.id = bank_entries.bank_id and b.owner_id = (select auth.uid())
  )
);

drop policy if exists "owners update bank entries" on public.bank_entries;
create policy "owners update bank entries"
on public.bank_entries for update
to authenticated
using (
  exists (
    select 1 from public.banks b
    where b.id = bank_entries.bank_id and b.owner_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.banks b
    where b.id = bank_entries.bank_id and b.owner_id = (select auth.uid())
  )
);

drop policy if exists "owners delete bank entries" on public.bank_entries;
create policy "owners delete bank entries"
on public.bank_entries for delete
to authenticated
using (
  exists (
    select 1 from public.banks b
    where b.id = bank_entries.bank_id and b.owner_id = (select auth.uid())
  )
);

create or replace function public.search_public_banks(search_term text default '', limit_count integer default 50)
returns table (
  id uuid,
  name text,
  subject text,
  description text,
  uploader_username text,
  entry_count bigint,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
stable
set search_path = ''
as $$
  select
    b.id,
    b.name,
    b.subject,
    b.description,
    p.username as uploader_username,
    count(e.id)::bigint as entry_count,
    b.created_at,
    b.updated_at
  from public.banks b
  join public.profiles p on p.id = b.owner_id
  left join public.bank_entries e on e.bank_id = b.id
  where b.visibility = 'public'
    and (
      coalesce(trim(search_term), '') = ''
      or b.name ilike '%' || trim(search_term) || '%'
      or b.subject ilike '%' || trim(search_term) || '%'
      or b.description ilike '%' || trim(search_term) || '%'
      or p.username ilike '%' || trim(search_term) || '%'
      or exists (
        select 1 from public.bank_entries se
        where se.bank_id = b.id
          and (se.term ilike '%' || trim(search_term) || '%' or se.definition ilike '%' || trim(search_term) || '%')
      )
    )
  group by b.id, p.username
  order by b.updated_at desc
  limit least(greatest(coalesce(limit_count, 50), 1), 100);
$$;

grant execute on function public.search_public_banks(text, integer) to anon, authenticated;
