'use strict';

/* TESTABLE_CORE_START */
function cleanBankType(type){return type==='multiple_choice'?'multiple_choice':'typelearning'}
function normalizeBank(bank,fallbackId='bank'){
  const type=cleanBankType(bank?.type||bank?.bank_type);
  const out={id:String(bank?.id||fallbackId),name:String(bank?.name||'Untitled Bank').trim()||'Untitled Bank',type,entries:[],...(bank?.community?{community:{...bank.community}}:{})};
  if(type==='multiple_choice'){
    out.entries=(Array.isArray(bank?.entries)?bank.entries:[]).map(e=>({question:String(e?.question??'').trim(),choices:(Array.isArray(e?.choices)?e.choices:[]).map(x=>String(x??'').trim()),correctIndex:Number.isInteger(e?.correctIndex)?e.correctIndex:Number(e?.correct_index),explanation:String(e?.explanation??'').trim()}));
  }else{
    out.entries=(Array.isArray(bank?.entries)?bank.entries:[]).map(e=>({term:String(e?.term??'').trim(),definition:String(e?.definition??'').trim()}));
  }
  return out;
}
function validateBank(bank){
  const errors=[];if(!bank||typeof bank!=='object')return{ok:false,errors:['Bank must be an object.']};
  if(!String(bank.name||'').trim())errors.push('Bank name is required.');
  const type=cleanBankType(bank.type);if(!Array.isArray(bank.entries)){errors.push('Entries must be an array.');return{ok:false,errors}}
  if(type==='typelearning')bank.entries.forEach((e,i)=>{if(!String(e?.term||'').trim()||!String(e?.definition||'').trim())errors.push(`Entry ${i+1}: term and definition are required.`)});
  else bank.entries.forEach((e,i)=>{const choices=Array.isArray(e?.choices)?e.choices:[];if(!String(e?.question||'').trim())errors.push(`Question ${i+1}: question text is required.`);if(choices.length<2||choices.length>6)errors.push(`Question ${i+1}: 2 to 6 choices are required.`);if(choices.some(c=>!String(c||'').trim()))errors.push(`Question ${i+1}: choices cannot be empty.`);if(!Number.isInteger(e?.correctIndex)||e.correctIndex<0||e.correctIndex>=choices.length)errors.push(`Question ${i+1}: correctIndex is out of range.`)});
  return{ok:!errors.length,errors};
}
function parseTextBank(text){const entries=[],errors=[],seen=new Set();String(text??'').split(/\r?\n/).forEach((raw,idx)=>{const line=raw.trim();if(!line)return;const splitAt=line.indexOf('|');if(splitAt<0){errors.push(`Line ${idx+1}: missing "|" separator.`);return}const term=line.slice(0,splitAt).trim(),definition=line.slice(splitAt+1).trim();if(!term||!definition){errors.push(`Line ${idx+1}: term and definition are both required.`);return}const key=`${term.toLocaleLowerCase()}\u0000${definition.toLocaleLowerCase()}`;if(seen.has(key)){errors.push(`Line ${idx+1}: duplicate entry skipped.`);return}seen.add(key);entries.push({term,definition})});return{entries,errors}}
function normalizeLearningText(text){return String(text??'').normalize('NFKC').toLocaleLowerCase().replace(/[\u2010-\u2015]/g,' ').replace(/[.,!?;:'"`~()[\]{}]/g,' ').replace(/\s+/g,' ').trim()}
function compareTexts(actual,expected,mode='strict'){const a=mode==='learning'?normalizeLearningText(actual):String(actual??''),e=mode==='learning'?normalizeLearningText(expected):String(expected??'');const max=Math.max(a.length,e.length);let same=0;for(let i=0;i<Math.min(a.length,e.length);i++)if(a[i]===e[i])same++;return{isExact:a===e,actual:a,expected:e,similarity:max?same/max:1}}
function shuffleCopy(items,rng=Math.random){const out=items.slice();for(let i=out.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function hashString(value){let h=0x811c9dc5;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,0x01000193)}return(h>>>0).toString(16).padStart(8,'0')}
function entryFingerprint(type,entry){type=cleanBankType(type);const canonical=type==='multiple_choice'?JSON.stringify(['mcq',String(entry?.question??'').trim(),...(Array.isArray(entry?.choices)?entry.choices.map(c=>String(c??'').trim()):[]),Number(entry?.correctIndex),String(entry?.explanation??'').trim()]):JSON.stringify(['tl',String(entry?.term??'').trim(),String(entry?.definition??'').trim()]);return hashString(canonical)}
function bankProgressKey(bank){return bank?.community?.bankId?`cloud:${bank.community.bankId}`:`local:${bank?.id||'unknown'}`}
function resetCoverageRecords(records,resetAt=new Date().toISOString()){const out={};for(const[k,v]of Object.entries(records||{}))out[k]=k==='__meta'?{...v}:{...v};out.__meta={...(out.__meta||{}),coverageResetAt:resetAt};return out}
function recordIsCovered(records,fingerprint){const r=records?.[fingerprint];if(!r||(r.encounterCount||0)<=0)return false;const resetAt=records?.__meta?.coverageResetAt;if(!resetAt)return true;return Boolean(r.lastEncounteredAt&&r.lastEncounteredAt>resetAt)}
function bankCoverage(bank,progress){const key=bankProgressKey(bank),records=progress?.[key]||{},total=bank?.entries?.length||0;let encountered=0;for(const entry of bank?.entries||[]){const h=entryFingerprint(bank.type,entry);if(recordIsCovered(records,h))encountered++}return{encountered,total,remaining:Math.max(0,total-encountered),percent:total?Math.round(encountered/total*1000)/10:0}}
function aggregateCoverage(banks,progress){let encountered=0,total=0;for(const bank of banks){const c=bankCoverage(bank,progress);encountered+=c.encountered;total+=c.total}return{encountered,total,remaining:Math.max(0,total-encountered),percent:total?Math.round(encountered/total*1000)/10:0}}
function enrichUnseenBanks(banks,progress){return banks.map(bank=>{const records=progress?.[bankProgressKey(bank)]||{};const entries=bank.entries.map((entry,entryIndex)=>({...entry,bankId:bank.id,bankName:bank.name,bankType:bank.type,entryIndex,entryFingerprint:entryFingerprint(bank.type,entry),progressKey:bankProgressKey(bank),communityBankId:bank.community?.bankId||null})).filter(e=>!recordIsCovered(records,e.entryFingerprint));return{...bank,entries}}).filter(b=>b.entries.length)}
function buildUnseenSequence(banks,config,progress,rng=Math.random){const enriched=enrichUnseenBanks(banks,progress),target=Math.max(0,Number(config?.targetCount)||0);if(!target||!enriched.length)return[];const result=[];if(config?.mixStrategy==='balanced'&&enriched.length>1){const queues=new Map(enriched.map(b=>[b.id,shuffleCopy(b.entries,rng)])),ids=shuffleCopy(enriched.map(b=>b.id),rng);let active=ids.slice();while(active.length&&result.length<target){const next=[];for(const id of active){const q=queues.get(id),item=q.shift();if(item)result.push({...item});if(q.length)next.push(id);if(result.length>=target)break}active=next}}else{const pool=shuffleCopy(enriched.flatMap(b=>b.entries),rng);result.push(...pool.slice(0,target).map(x=>({...x})))}return result}
function computeStats({elapsedMs=0,correctChars=0,incorrectChars=0,rawChars=0,samples=[]}){const minutes=Math.max(elapsedMs,1)/60000,wpm=+(correctChars/5/minutes).toFixed(2),rawWpm=+(rawChars/5/minutes).toFixed(2),denom=correctChars+incorrectChars,accuracy=+(denom?correctChars/denom*100:100).toFixed(2);let consistency=100;if(samples.length>1){const mean=samples.reduce((a,b)=>a+b,0)/samples.length,variance=samples.reduce((a,b)=>a+(b-mean)**2,0)/samples.length,sd=Math.sqrt(variance);consistency=mean>0?Math.max(0,Math.min(100,100-(sd/mean)*100)):100}return{wpm,rawWpm,accuracy,consistency:+consistency.toFixed(2)}}
function classifyTypingChars(input,reference){input=String(input??'');reference=String(reference??'');return Array.from(reference,(ch,i)=>i<input.length?(input[i]===ch?'correct':'incorrect'):'pending')}
function makeTypingTarget(term,definition){term=String(term??'');definition=String(definition??'');return{term,definition,expected:term+definition,termLength:term.length,definitionLength:definition.length,totalLength:term.length+definition.length}}
function splitTypingInput(input,termLength,definitionLength){input=String(input??'');const start=Math.max(0,termLength);return{termInput:input.slice(0,start),definitionInput:input.slice(start,start+Math.max(0,definitionLength))}}
/* TESTABLE_CORE_END */

const STORAGE={banks:'eceTypeReview.banks.v3',settings:'eceTypeReview.settings.v3',history:'eceTypeReview.history.v3',progress:'eceTypeReview.progress.v1',legacyBanks:'eceTypeReview.banks.v2',legacySettings:'eceTypeReview.settings.v2',legacyHistory:'eceTypeReview.history.v2'};
const DEFAULT_BANKS=[{id:'demo-electronics',name:'Demo — Electronics Basics',type:'typelearning',entries:[{term:"Ohm's Law",definition:'The voltage across a conductor equals the current through it multiplied by its resistance.'},{term:'Reactance',definition:'The opposition that capacitance or inductance presents to alternating current.'},{term:'Bandwidth',definition:'The range of frequencies occupied, passed, or supported by a system.'},{term:'Kirchhoff’s Current Law',definition:'The algebraic sum of currents entering and leaving a node is zero.'},{term:'Gain',definition:'The ratio of an output signal quantity to the corresponding input signal quantity.'}]},{id:'demo-mcq',name:'Demo — ECE Multiple Choice',type:'multiple_choice',entries:[{question:'Which relationship represents Ohm\'s Law?',choices:['V = IR','P = VI','f = 1 / T','Q = CV'],correctIndex:0,explanation:'Ohm\'s Law states that voltage equals current multiplied by resistance.'},{question:'Which quantity is measured in hertz?',choices:['Resistance','Frequency','Capacitance','Power'],correctIndex:1,explanation:'Hertz is the SI unit of frequency.'}]}];
const DEFAULT_SETTINGS={bankType:'typelearning',studyMode:'typing',sessionType:'definitions',definitionPreset:'10',customDefinitionCount:10,timePreset:'60',customTime:60,bankSource:'single',singleBankId:'demo-electronics',selectedBankIds:['demo-electronics'],mixStrategy:'random',matchMode:'strict',allowCorrections:true,revealAllowed:true,shuffleChoices:true,showExplanations:true};
const state={banks:[],settings:{...DEFAULT_SETTINGS},history:[],progress:{},activeBankId:null,session:null,lastSession:null,view:'setup',toastTimer:null,mcqEditorIndex:0};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function safeParse(raw,fallback){try{return raw?JSON.parse(raw):fallback}catch{return fallback}}
function makeId(prefix='bank'){return`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function filenameSafe(name){return String(name||'bank').replace(/[^a-z0-9-_]+/gi,'_').replace(/^_+|_+$/g,'')||'bank'}
function notify(msg){const t=$('#toast');if(!t){console.info(msg);return}t.textContent=msg;t.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}
function storageWrite(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{notify('Browser storage is unavailable or full. Export a backup before continuing.');return false}}
function saveBanks(){return storageWrite(STORAGE.banks,state.banks)}function saveSettings(){return storageWrite(STORAGE.settings,state.settings)}function saveHistory(){return storageWrite(STORAGE.history,state.history)}function saveProgress(){return storageWrite(STORAGE.progress,state.progress)}
function loadPersistedState(){
  const rawBanks=safeParse(localStorage.getItem(STORAGE.banks),null)||safeParse(localStorage.getItem(STORAGE.legacyBanks),null);state.banks=(Array.isArray(rawBanks)&&rawBanks.length?rawBanks:structuredClone(DEFAULT_BANKS)).map((b,i)=>normalizeBank(b,b.id||`bank-${i}`));
  state.settings={...DEFAULT_SETTINGS,...(safeParse(localStorage.getItem(STORAGE.settings),null)||safeParse(localStorage.getItem(STORAGE.legacySettings),{}))};delete state.settings.repeatPolicy;
  state.history=safeParse(localStorage.getItem(STORAGE.history),null)||safeParse(localStorage.getItem(STORAGE.legacyHistory),[])||[];if(!Array.isArray(state.history))state.history=[];
  state.progress=safeParse(localStorage.getItem(STORAGE.progress),{})||{};
  ensureCompatibleSelection();state.activeBankId=state.settings.singleBankId||state.banks[0]?.id||null;saveBanks();saveSettings();
}
function compatibleBanks(type=state.settings.bankType){return state.banks.filter(b=>cleanBankType(b.type)===cleanBankType(type))}
function ensureCompatibleSelection(){const list=compatibleBanks();if(!list.some(b=>b.id===state.settings.singleBankId))state.settings.singleBankId=list[0]?.id||'';state.settings.selectedBankIds=(state.settings.selectedBankIds||[]).filter(id=>list.some(b=>b.id===id));if(!state.settings.selectedBankIds.length&&list[0])state.settings.selectedBankIds=[list[0].id]}
function uniqueBankName(name,excludeId=null){const base=String(name||'Untitled Bank').trim();if(!state.banks.some(b=>b.id!==excludeId&&b.name===base))return base;let n=2;while(state.banks.some(b=>b.id!==excludeId&&b.name===`${base} (${n})`))n++;return`${base} (${n})`}
function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function bankTypeLabel(type){return cleanBankType(type)==='multiple_choice'?'MULTIPLE CHOICE':'TYPELEARNING'}
function bankUnitLabel(type,count=2){return cleanBankType(type)==='multiple_choice'?(count===1?'question':'questions'):(count===1?'definition':'definitions')}
function bankToText(bank){return bank.entries.map(e=>`${e.term} | ${e.definition}`).join('\n')}
function getBankProgress(bank){return state.progress[bankProgressKey(bank)]||{}}
function coverageForBank(bank){return bankCoverage(bank,state.progress)}
function aggregateSelectedCoverage(banks){return aggregateCoverage(banks,state.progress)}
function updateLocalProgress(entry,delta={}){const key=entry.progressKey||`local:${entry.bankId}`,fingerprint=entry.entryFingerprint;state.progress[key] ||= {};const r=state.progress[key][fingerprint]||{encounterCount:0,correctCount:0,incorrectCount:0,revealedCount:0,lastEncounteredAt:null};for(const field of ['encounterCount','correctCount','incorrectCount','revealedCount'])r[field]=Math.max(0,(r[field]||0)+(delta[field]||0));if(delta.lastEncounteredAt)r.lastEncounteredAt=delta.lastEncounteredAt;state.progress[key][fingerprint]=r;saveProgress();if(entry.communityBankId&&window.ECECloud?.recordProgress)window.ECECloud.recordProgress(entry.communityBankId,fingerprint,delta).catch(console.error);return r}
function markEncounter(entry){updateLocalProgress(entry,{encounterCount:1,lastEncounteredAt:new Date().toISOString()});renderCoverageSummary(false)}
function markOutcome(entry,status){const d={};if(status==='completed'||status==='correct')d.correctCount=1;if(status==='missed'||status==='incorrect')d.incorrectCount=1;if(status==='revealed'){d.incorrectCount=1;d.revealedCount=1}if(Object.keys(d).length)updateLocalProgress(entry,d)}
function resetBankCoverage(bank){const key=bankProgressKey(bank),resetAt=new Date().toISOString();state.progress[key]=resetCoverageRecords(state.progress[key]||{},resetAt);saveProgress();if(bank.community?.bankId&&window.ECECloud?.resetBankCoverage)window.ECECloud.resetBankCoverage(bank.community.bankId,resetAt).catch(console.error);renderSetup();renderBankManager()}
function mergeCloudProgress(bankId,rows,bankState=null){const key=`cloud:${bankId}`;state.progress[key] ||= {};for(const row of rows||[]){const h=row.entry_fingerprint||row.entryFingerprint;if(!h)continue;const local=state.progress[key][h]||{};state.progress[key][h]={encounterCount:Math.max(local.encounterCount||0,row.encounter_count||0),correctCount:Math.max(local.correctCount||0,row.correct_count||0),incorrectCount:Math.max(local.incorrectCount||0,row.incorrect_count||0),revealedCount:Math.max(local.revealedCount||0,row.revealed_count||0),lastEncounteredAt:[local.lastEncounteredAt,row.last_encountered_at].filter(Boolean).sort().pop()||null}}const localReset=state.progress[key].__meta?.coverageResetAt,remoteReset=bankState?.coverage_reset_at||bankState?.coverageResetAt;const coverageResetAt=[localReset,remoteReset].filter(Boolean).sort().pop()||null;if(coverageResetAt)state.progress[key].__meta={...(state.progress[key].__meta||{}),coverageResetAt};saveProgress();renderSetup();renderBankManager();return structuredClone(state.progress[key])}
function getCloudProgressPayload(bankId){return structuredClone(state.progress[`cloud:${bankId}`]||{})}
function linkActiveBankToCommunity(bankId,uploader,subject){const b=state.banks.find(x=>x.id===state.activeBankId);if(!b)return null;const oldKey=bankProgressKey(b);b.community={bankId,uploader:uploader||'',subject:subject||''};const newKey=bankProgressKey(b);if(oldKey!==newKey&&state.progress[oldKey]){state.progress[newKey]={...(state.progress[newKey]||{}),...state.progress[oldKey]};delete state.progress[oldKey];saveProgress()}saveBanks();renderSetup();renderBankManager();return structuredClone(b)}
function renderProgressBar(c){return`<div class="coverage-line"><div class="coverage-track"><span style="width:${Math.min(100,c.percent)}%"></span></div><span>${c.percent.toFixed(1)}%</span></div>`}

function getSelectedBanks(settings=state.settings){const list=compatibleBanks(settings.bankType);if(settings.bankSource==='all')return list;if(settings.bankSource==='selected')return list.filter(b=>settings.selectedBankIds.includes(b.id));return list.filter(b=>b.id===settings.singleBankId)}
function updateModeDefault(previous,newMode){if(previous!==newMode)state.settings.matchMode=newMode==='recall'?'learning':'strict'}
function renderCoverageSummary(includeReset=true){const host=$('#coverageSummary');if(!host)return;const banks=getSelectedBanks(),c=aggregateSelectedCoverage(banks);host.innerHTML=banks.length?`<div class="coverage-title"><span>bank coverage</span><strong>${c.encountered} / ${c.total}</strong></div>${renderProgressBar(c)}<div class="subtle">${c.remaining} unseen ${bankUnitLabel(state.settings.bankType,c.remaining)} remaining</div>`:'<div class="subtle">Select a compatible bank to see coverage.</div>'}
function renderSetup(){
  ensureCompatibleSelection();const s=state.settings;$$('#setupView [data-setting]').forEach(group=>{const key=group.dataset.setting;group.querySelectorAll('[data-value]').forEach(b=>b.classList.toggle('active',b.dataset.value===s[key]))});
  $('#studyModeSegment').classList.toggle('hidden',s.bankType!=='typelearning');$('#studyModeDivider').classList.toggle('hidden',s.bankType!=='typelearning');$('#countModeLabel').textContent=s.bankType==='multiple_choice'?'questions':'definitions';
  const defs=['5','10','20','50','all','custom'],times=['15','30','60','120','custom'];$('#definitionPresets').innerHTML=defs.map(v=>`<button class="seg-btn ${s.definitionPreset===v?'active':''}" data-preset="definition" data-value="${v}">${v}</button>`).join('');$('#timePresets').innerHTML=times.map(v=>`<button class="seg-btn ${s.timePreset===v?'active':''}" data-preset="time" data-value="${v}">${v==='custom'?'custom':v+'s'}</button>`).join('');$('#definitionPresets').classList.toggle('hidden',s.sessionType!=='definitions');$('#timePresets').classList.toggle('hidden',s.sessionType!=='time');
  $('#bankSource').value=s.bankSource;$('#matchMode').value=s.matchMode;$('#allowCorrections').checked=s.allowCorrections;$('#revealAllowed').checked=s.revealAllowed;$('#shuffleChoices').checked=s.shuffleChoices;$('#showExplanations').checked=s.showExplanations;
  const banks=compatibleBanks();$('#singleBank').innerHTML=banks.length?banks.map(b=>{const c=coverageForBank(b);return`<option value="${esc(b.id)}">${esc(b.name)} — ${c.percent.toFixed(0)}%</option>`}).join(''):'<option value="">No compatible banks loaded</option>';$('#singleBank').value=s.singleBankId;
  $('#selectedBanksChecks').innerHTML=banks.map(b=>{const c=coverageForBank(b);return`<label class="check"><input type="checkbox" data-bank-check="${esc(b.id)}" ${s.selectedBankIds.includes(b.id)?'checked':''}/> ${esc(b.name)} <span>(${c.percent.toFixed(0)}%)</span></label>`}).join('')||'<span class="subtle">No compatible banks loaded.</span>';
  $('#singleBankField').classList.toggle('hidden',s.bankSource!=='single');$('#selectedBanksField').classList.toggle('hidden',s.bankSource!=='selected');$('#mixOptions').classList.toggle('hidden',s.bankSource==='single');
  const custom=s.sessionType==='definitions'?s.definitionPreset==='custom':s.timePreset==='custom';$('#customLengthField').classList.toggle('hidden',!custom);$('#customLengthLabel').textContent=s.sessionType==='definitions'?`custom ${bankUnitLabel(s.bankType)}`:'custom seconds';$('#customLength').value=s.sessionType==='definitions'?s.customDefinitionCount:s.customTime;
  const tl=s.bankType==='typelearning';$('#typelearningOptions').classList.toggle('hidden',!tl);$('#mcqOptions').classList.toggle('hidden',tl);
  const selected=getSelectedBanks(),c=aggregateSelectedCoverage(selected);$('#activePoolCount').textContent=`${c.remaining} unseen ${bankUnitLabel(s.bankType,c.remaining)}`;renderCoverageSummary();
  const notice=[];if(!selected.length)notice.push(`Load or select at least one ${bankTypeLabel(s.bankType)} bank.`);else if(!c.remaining)notice.push('Selected bank coverage is complete. Reset coverage to begin another full pass.');else if(s.sessionType==='definitions'){const requested=s.definitionPreset==='all'?c.remaining:s.definitionPreset==='custom'?Number(s.customDefinitionCount)||1:Number(s.definitionPreset)||10;if(requested>c.remaining)notice.push(`Only ${c.remaining} unseen ${bankUnitLabel(s.bankType,c.remaining)} remain, so this session will use those ${c.remaining}.`)}$('#setupNotice').textContent=notice.join(' ');
}
function switchView(name){state.view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));window.scrollTo({top:0,behavior:'smooth'})}

function mutateBanks(mutator){const old=structuredClone(state.banks);mutator();if(!saveBanks()){state.banks=old;return false}ensureCompatibleSelection();saveSettings();renderSetup();renderBankManager();return true}
function renderBankManager(){
  if(state.activeBankId&&!state.banks.some(b=>b.id===state.activeBankId))state.activeBankId=state.banks[0]?.id||null;$('#bankList').innerHTML=state.banks.map(b=>{const c=coverageForBank(b);return`<button class="bank-item ${b.id===state.activeBankId?'active':''}" data-bank-id="${esc(b.id)}"><span><span class="bank-badge ${b.type==='multiple_choice'?'mcq':''}">${b.type==='multiple_choice'?'MCQ':'TL'}</span> ${esc(b.name)}</span><small>${c.percent.toFixed(0)}%</small></button>`}).join('')||'<span class="subtle">No banks yet.</span>';
  const b=state.banks.find(x=>x.id===state.activeBankId),disabled=!b;$('#bankNameEditor').disabled=disabled;['saveBankBtn','duplicateBankBtn','exportJsonBtn','deleteBankBtn','resetCoverageBtn'].forEach(id=>$('#'+id).disabled=disabled);$('#exportTxtBtn').disabled=disabled||b?.type!=='typelearning';
  if(!b){$('#bankNameEditor').value='';$('#bankEditorMeta').textContent='Create or import a bank to begin.';$('#typelearningEditor').classList.add('hidden');$('#mcqEditor').classList.add('hidden');$('#bankCoverageBox').innerHTML='';return}
  $('#bankNameEditor').value=b.name;const c=coverageForBank(b);$('#bankEditorMeta').innerHTML=`<span class="bank-badge ${b.type==='multiple_choice'?'mcq':''}">${bankTypeLabel(b.type)}</span> • ${b.entries.length} ${bankUnitLabel(b.type,b.entries.length)}`;$('#bankCoverageBox').innerHTML=`<div class="coverage-title"><span>coverage</span><strong>${c.encountered} / ${c.total}</strong></div>${renderProgressBar(c)}<div class="subtle">Reset makes every ${bankUnitLabel(b.type,1)} encounterable again while keeping lifetime answer history.</div>`;
  $('#typelearningEditor').classList.toggle('hidden',b.type!=='typelearning');$('#mcqEditor').classList.toggle('hidden',b.type!=='multiple_choice');$('#bankErrors').textContent='';if(b.type==='typelearning'){$('#bankTextEditor').value=bankToText(b);$('#typelearningEditorMeta').textContent='plain text format: Term | Definition'}else renderMcqEditor(b);
}
function newBank(type){type=cleanBankType(type);const id=makeId(),name=uniqueBankName(type==='multiple_choice'?'New Multiple Choice Bank':'New TypeLearning Bank');mutateBanks(()=>state.banks.push({id,name,type,entries:[]}));state.activeBankId=id;state.settings.bankType=type;state.settings.singleBankId=id;state.settings.selectedBankIds=[id];saveSettings();state.mcqEditorIndex=0;renderSetup();renderBankManager();$('#bankNameEditor').focus()}
function duplicateBank(){const b=state.banks.find(x=>x.id===state.activeBankId);if(!b)return;const copy={id:makeId(),name:uniqueBankName(`${b.name} Copy`),type:b.type,entries:structuredClone(b.entries)};mutateBanks(()=>state.banks.push(copy));state.activeBankId=copy.id;state.settings.bankType=copy.type;state.settings.singleBankId=copy.id;saveSettings();renderSetup();renderBankManager();notify('Bank duplicated with fresh coverage.')}
function deleteBank(){const b=state.banks.find(x=>x.id===state.activeBankId);if(!b||!confirm(`Delete "${b.name}"?`))return;const key=bankProgressKey(b);mutateBanks(()=>{state.banks=state.banks.filter(x=>x.id!==b.id);delete state.progress[key];saveProgress();state.activeBankId=state.banks[0]?.id||null;state.settings.selectedBankIds=state.settings.selectedBankIds.filter(id=>id!==b.id)});notify('Bank deleted.')}
function saveActiveBank(){const b=state.banks.find(x=>x.id===state.activeBankId);if(!b)return;const name=$('#bankNameEditor').value.trim();const errs=[];if(!name)errs.push('Bank name is required.');const dup=state.banks.find(x=>x.id!==b.id&&x.name.toLocaleLowerCase()===name.toLocaleLowerCase());if(dup)errs.push(`A bank named "${name}" already exists.`);let entries=b.entries;if(b.type==='typelearning'){const parsed=parseTextBank($('#bankTextEditor').value);entries=parsed.entries;errs.push(...parsed.errors);if(!entries.length)errs.push('At least one valid entry is required.')}$('#bankErrors').textContent=errs.join('\n');if(!name||dup||!entries.length)return;mutateBanks(()=>{b.name=name;b.entries=entries});notify(errs.length?'Bank saved; invalid lines were skipped.':'Bank saved.')}
function renderMcqEditor(bank){const entries=bank.entries;if(state.mcqEditorIndex>=entries.length)state.mcqEditorIndex=Math.max(0,entries.length-1);$('#mcqQuestionList').innerHTML=entries.length?entries.map((e,i)=>`<option value="${i}">${i+1}. ${esc(e.question.slice(0,70))}</option>`).join(''):'<option value="-1">No questions yet</option>';$('#mcqQuestionList').value=entries.length?String(state.mcqEditorIndex):'-1';const e=entries[state.mcqEditorIndex];fillMcqForm(e||null);$('#mcqEditorMeta').textContent=entries.length?`${state.mcqEditorIndex+1} of ${entries.length}`:'Create the first question.'}
function fillMcqForm(entry){$('#mcqQuestionText').value=entry?.question||'';$('#mcqExplanation').value=entry?.explanation||'';const choices=entry?.choices?.length?entry.choices.slice():['','','',''];const correct=Number.isInteger(entry?.correctIndex)?entry.correctIndex:0;renderMcqChoicesEditor(choices,correct)}
function renderMcqChoicesEditor(choices,correctIndex){$('#mcqChoicesEditor').innerHTML=choices.map((choice,i)=>`<div class="mcq-edit-choice"><input type="radio" name="mcqCorrect" value="${i}" ${i===correctIndex?'checked':''} aria-label="Mark choice ${i+1} correct"/><span class="choice-number">${i+1}</span><input type="text" data-mcq-choice="${i}" value="${esc(choice)}" placeholder="Choice ${i+1}"/><button type="button" class="icon-btn remove-mcq-choice" data-remove-choice="${i}" ${choices.length<=2?'disabled':''}>×</button></div>`).join('')}
function readMcqForm(){const question=$('#mcqQuestionText').value.trim(),choices=$$('[data-mcq-choice]').map(x=>x.value.trim()),correct=Number($('input[name="mcqCorrect"]:checked')?.value),explanation=$('#mcqExplanation').value.trim();return{question,choices,correctIndex:correct,explanation}}
function saveMcqQuestion(){const b=state.banks.find(x=>x.id===state.activeBankId);if(!b||b.type!=='multiple_choice')return;const entry=readMcqForm(),v=validateBank({name:'x',type:'multiple_choice',entries:[entry]});if(!v.ok){$('#bankErrors').textContent=v.errors.join('\n');return}mutateBanks(()=>{if(state.mcqEditorIndex>=0&&state.mcqEditorIndex<b.entries.length)b.entries[state.mcqEditorIndex]=entry;else{b.entries.push(entry);state.mcqEditorIndex=b.entries.length-1}});$('#bankErrors').textContent='';notify('Question saved.')}
function newMcqQuestion(){state.mcqEditorIndex=-1;$('#mcqQuestionList').value='-1';fillMcqForm(null);$('#mcqEditorMeta').textContent='New unsaved question';$('#mcqQuestionText').focus()}
function duplicateMcqQuestion(){const b=state.banks.find(x=>x.id===state.activeBankId),e=b?.entries?.[state.mcqEditorIndex];if(!e)return;mutateBanks(()=>{b.entries.push(structuredClone(e));state.mcqEditorIndex=b.entries.length-1});renderBankManager();notify('Question duplicated.')}
function deleteMcqQuestion(){const b=state.banks.find(x=>x.id===state.activeBankId),e=b?.entries?.[state.mcqEditorIndex];if(!e||!confirm('Delete this question?'))return;mutateBanks(()=>b.entries.splice(state.mcqEditorIndex,1));state.mcqEditorIndex=Math.max(0,state.mcqEditorIndex-1);renderBankManager();notify('Question deleted.')}
function addMcqChoice(){const form=readMcqForm();if(form.choices.length>=6){notify('MCQ questions support up to 6 choices.');return}form.choices.push('');renderMcqChoicesEditor(form.choices,Number.isInteger(form.correctIndex)?form.correctIndex:0)}
function removeMcqChoice(index){const form=readMcqForm();if(form.choices.length<=2)return;const oldCorrect=form.correctIndex;form.choices.splice(index,1);let correct=oldCorrect;if(index===oldCorrect)correct=0;else if(index<oldCorrect)correct--;renderMcqChoicesEditor(form.choices,correct)}
function exportBankText(bank){if(bank.type!=='typelearning'){notify('TXT export is available for TypeLearning banks only.');return}download(`${filenameSafe(bank.name)}.txt`,bankToText(bank),'text/plain;charset=utf-8')}
function exportBankJson(bank){download(`${filenameSafe(bank.name)}.json`,JSON.stringify({name:bank.name,type:bank.type,entries:bank.entries},null,2),'application/json')}
function exportBackup(){download(`ece_type_review_backup_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({schema:'ece-typing-reviewer-backup',version:2,banks:state.banks,settings:state.settings,history:state.history,progress:state.progress},null,2),'application/json')}
async function importFiles(files){const existingNames=new Set(state.banks.map(b=>b.name.toLocaleLowerCase())),additions=[],messages=[];for(const file of files){try{const text=await file.text();if(file.name.toLowerCase().endsWith('.txt')){const p=parseTextBank(text),name=file.name.replace(/\.txt$/i,'').replace(/[_-]+/g,' ').trim()||'Imported Bank';if(!p.entries.length){messages.push(`${file.name}: no valid entries.`);continue}if(existingNames.has(name.toLocaleLowerCase())){messages.push(`${file.name}: duplicate bank name "${name}".`);continue}additions.push({id:makeId(),name,type:'typelearning',entries:p.entries});existingNames.add(name.toLocaleLowerCase());if(p.errors.length)messages.push(`${file.name}: ${p.errors.length} invalid line(s) skipped.`)}else{const data=JSON.parse(text);if(data?.schema==='ece-typing-reviewer-backup'){const candidate=(Array.isArray(data.banks)?data.banks:[]).map((b,i)=>normalizeBank(b,b.id||makeId()));const invalid=candidate.flatMap((b,i)=>validateBank(b).errors.map(e=>`Bank ${i+1}: ${e}`));if(invalid.length){messages.push(`${file.name}: backup rejected — ${invalid[0]}`);continue}state.banks=candidate;state.settings={...DEFAULT_SETTINGS,...(data.settings||{})};delete state.settings.repeatPolicy;state.history=Array.isArray(data.history)?data.history.slice(0,100):[];state.progress=data.version>=2&&data.progress&&typeof data.progress==='object'?data.progress:{};ensureCompatibleSelection();state.activeBankId=state.banks[0]?.id||null;saveBanks();saveSettings();saveHistory();saveProgress();messages.push(`${file.name}: backup restored.`);continue}const bank=normalizeBank(data,makeId()),v=validateBank(bank);if(!v.ok){messages.push(`${file.name}: ${v.errors[0]}`);continue}if(existingNames.has(bank.name.toLocaleLowerCase())){messages.push(`${file.name}: duplicate bank name "${bank.name}".`);continue}bank.id=makeId();additions.push(bank);existingNames.add(bank.name.toLocaleLowerCase())}}catch(err){messages.push(`${file.name}: ${err.message}`)}}if(additions.length)mutateBanks(()=>state.banks.push(...additions));if(additions.length){state.activeBankId=additions[additions.length-1].id;state.settings.bankType=additions[additions.length-1].type;state.settings.singleBankId=state.activeBankId;saveSettings()}renderBankManager();renderSetup();notify(messages.length?messages.join(' • '):`${additions.length} bank(s) imported.`)}

function desiredTargetCount(config,banks){const unseen=aggregateCoverage(banks,state.progress).remaining;if(config.sessionType==='time')return unseen;if(config.definitionPreset==='all')return unseen;return Math.min(unseen,Math.max(1,config.definitionPreset==='custom'?Number(config.customDefinitionCount)||1:Number(config.definitionPreset)||10))}
function findOrderedEntries(banks,order){const lookup=new Map();for(const bank of banks)bank.entries.forEach((entry,entryIndex)=>{const h=entryFingerprint(bank.type,entry);lookup.set(`${bank.id}:${h}`,{...entry,bankId:bank.id,bankName:bank.name,bankType:bank.type,entryIndex,entryFingerprint:h,progressKey:bankProgressKey(bank),communityBankId:bank.community?.bankId||null})});return(order||[]).map(k=>lookup.get(k)).filter(Boolean)}
function startSession(options={}){const config=options.config?structuredClone(options.config):structuredClone(state.settings),banks=getSelectedBanks(config);if(!banks.length){notify('Select at least one compatible bank.');return}const coverageBefore=aggregateCoverage(banks,state.progress);let queue=options.order?findOrderedEntries(banks,options.order):buildUnseenSequence(banks,{...config,targetCount:desiredTargetCount(config,banks)},state.progress);if(!queue.length){notify('Bank coverage is complete. Reset coverage to start another pass.');renderSetup();return}const now=performance.now();state.session={config,banks,queue,index:0,processed:0,startedAt:now,itemStartedAt:now,paused:false,pauseStartedAt:0,pausedMs:0,timerId:null,sampleTimer:null,rawChars:0,correctChars:0,incorrectChars:0,completed:0,missed:0,revealed:0,incomplete:0,samples:[],accuracySamples:[],subjectStats:{},feedback:false,lastInput:'',ended:false,coverageBefore,mcqCorrect:0,mcqIncorrect:0,responseTimes:[],currentMcqDisplay:null};$('#pauseBtn').classList.toggle('hidden',config.sessionType==='time');$('#pausedOverlay').classList.add('hidden');switchView('session');renderSessionEntry();startSessionTimers()}
function startSessionTimers(){const s=state.session;if(!s)return;clearInterval(s.timerId);clearInterval(s.sampleTimer);s.timerId=setInterval(tickSession,100);s.sampleTimer=setInterval(recordSample,1000)}
function elapsedMs(){const s=state.session;if(!s)return 0;const now=performance.now();return Math.max(0,(s.ended?s.endedAt:now)-s.startedAt-s.pausedMs-(s.paused?now-s.pauseStartedAt:0))}
function currentEntry(){return state.session?.queue[state.session.index]||null}
function renderSessionEntry(){const s=state.session,e=currentEntry();if(!s||!e){endSession();return}s.feedback=false;s.lastInput='';s.itemStartedAt=performance.now();$('#subjectLabel').textContent=`${e.bankName} • ${bankTypeLabel(e.bankType)}`;$('#typingArea').classList.add('hidden');$('#recallArea').classList.add('hidden');$('#mcqArea').classList.add('hidden');markEncounter(e);if(e.bankType==='multiple_choice'){renderMcqEntry(e)}else if(s.config.studyMode==='typing'){renderTypingEntry(e)}else renderRecallEntry(e);updateProgress()}
function renderTypingEntry(e){$('#typingArea').classList.remove('hidden');const target=makeTypingTarget(e.term,e.definition);$('#typingCapture').maxLength=target.totalLength;$('#typingCapture').value='';renderTypingTerm('',e.term,true);renderTypingText('',e.definition,true,false);setTimeout(()=>$('#typingCapture').focus(),0)}
function renderRecallEntry(e){const s=state.session;$('#recallArea').classList.remove('hidden');$('#revealBtn').classList.toggle('hidden',!s.config.revealAllowed);$('#answerPanel').classList.add('hidden');$('#recallActionRow').classList.remove('hidden');$('#recallInput').value='';$('#recallTerm').textContent=e.term;setTimeout(()=>$('#recallInput').focus(),0)}
function renderMcqEntry(e){const s=state.session;$('#mcqArea').classList.remove('hidden');$('#mcqQuestion').textContent=e.question;$('#mcqExplanationPanel').classList.add('hidden');$('#mcqExplanation').textContent='';$('#mcqNextBtn').classList.add('hidden');const display=e.choices.map((text,originalIndex)=>({text,originalIndex}));s.currentMcqDisplay=s.config.shuffleChoices?shuffleCopy(display):display;$('#mcqChoices').innerHTML=s.currentMcqDisplay.map((choice,i)=>`<button class="mcq-choice" data-mcq-original="${choice.originalIndex}"><span>${i+1}</span><strong>${esc(choice.text)}</strong></button>`).join('')}
function buildCharReference(container,reference,{charClass,spaceClass,wordClass,endClass,stateClass,indexAttr}){const chunks=reference.match(/\S+\s*|\s+/g)||[];let index=0,html='';for(const chunk of chunks){const wrapper=/^\s+$/.test(chunk)?`${wordClass}-whitespace`:wordClass;html+=`<span class="${wrapper}">`;for(const ch of chunk){const space=/\s/.test(ch),shown=ch===' '?'\u00a0':ch==='\t'?'\u00a0\u00a0\u00a0\u00a0':ch;html+=`<span class="${charClass}${space?' '+spaceClass:''} ${stateClass}" ${indexAttr}="${index}">${esc(shown)}</span>`;index++}html+='</span>'}html+=`<span class="${endClass}" ${indexAttr}="${reference.length}"></span>`;container.innerHTML=html;container.dataset.reference=reference}
function buildTypingTerm(reference){const term=$('#typingTerm');buildCharReference(term,reference,{charClass:'term-char',spaceClass:'term-space',wordClass:'term-word',endClass:'term-end-anchor',stateClass:'term-pending',indexAttr:'data-term-char-index'});term.insertAdjacentHTML('beforeend','<span class="typing-term-caret" id="typingTermCaret" aria-hidden="true"></span>')}
function moveTypingTermCaret(index,instant=false){const term=$('#typingTerm'),caret=$('#typingTermCaret');if(!term||!caret)return;if(index>=Number(term.dataset.reference?.length||0)){caret.style.visibility='hidden';return}const anchor=term.querySelector(`[data-term-char-index="${index}"]`)||term.querySelector('.term-end-anchor');if(!anchor)return;caret.style.visibility='visible';const tr=term.getBoundingClientRect(),ar=anchor.getBoundingClientRect(),x=ar.left-tr.left,h=Math.max(24,ar.height||parseFloat(getComputedStyle(term).fontSize)),y=ar.top-tr.top+Math.max(0,(ar.height-h)/2);if(instant){caret.style.transition='none';caret.style.transform=`translate3d(${x}px,${y}px,0)`;caret.style.height=`${h}px`;requestAnimationFrame(()=>{caret.style.transition=''})}else{caret.style.transform=`translate3d(${x}px,${y}px,0)`;caret.style.height=`${h}px`}caret.classList.add('moving');clearTimeout(moveTypingTermCaret._idleTimer);moveTypingTermCaret._idleTimer=setTimeout(()=>caret.classList.remove('moving'),140)}
function renderTypingTerm(input,reference,reset=false){const term=$('#typingTerm');if(reset||term.dataset.reference!==reference)buildTypingTerm(reference);const states=classifyTypingChars(input,reference),chars=term.querySelectorAll('.term-char');chars.forEach((node,i)=>{node.classList.remove('term-pending','term-correct','term-incorrect');node.classList.add(`term-${states[i]}`)});const caretIndex=Math.min(input.length,reference.length);if(reset){const caret=$('#typingTermCaret');if(caret)caret.style.visibility='hidden';requestAnimationFrame(()=>requestAnimationFrame(()=>moveTypingTermCaret(caretIndex,true)))}else moveTypingTermCaret(caretIndex,false)}
function buildTypingReference(reference){buildCharReference($('#typingText'),reference,{charClass:'typing-char',spaceClass:'typing-space',wordClass:'typing-word',endClass:'typing-end-anchor',stateClass:'pending',indexAttr:'data-char-index'})}
function moveTypingCaret(index,instant=false){const stage=$('#typingStage'),text=$('#typingText'),caret=$('#typingCaret'),anchor=text.querySelector(`[data-char-index="${index}"]`)||text.querySelector('.typing-end-anchor');if(!stage||!anchor||!caret)return;const sr=stage.getBoundingClientRect(),ar=anchor.getBoundingClientRect(),x=ar.left-sr.left,h=Math.max(20,ar.height||parseFloat(getComputedStyle(stage).fontSize)*1.2),y=ar.top-sr.top+Math.max(0,(ar.height-h)/2);if(instant){caret.style.transition='none';caret.style.transform=`translate3d(${x}px,${y}px,0)`;caret.style.height=`${h}px`;requestAnimationFrame(()=>{caret.style.transition=''})}else{caret.style.transform=`translate3d(${x}px,${y}px,0)`;caret.style.height=`${h}px`}caret.classList.add('moving');clearTimeout(moveTypingCaret._idleTimer);moveTypingCaret._idleTimer=setTimeout(()=>caret.classList.remove('moving'),140)}
function renderTypingText(input,reference,reset=false,active=true){const text=$('#typingText'),caret=$('#typingCaret');if(reset||text.dataset.reference!==reference)buildTypingReference(reference);const states=classifyTypingChars(input,reference),chars=text.querySelectorAll('.typing-char');chars.forEach((node,i)=>{node.classList.remove('pending','correct','incorrect');node.classList.add(states[i])});caret.style.visibility=active?'visible':'hidden';if(active)moveTypingCaret(Math.min(input.length,reference.length),reset)}
function rawCharDelta(prev,next){let common=0;while(common<prev.length&&common<next.length&&prev[common]===next[common])common++;return Math.max(0,next.length-common)}
function charMetrics(actual,expected,mode){const c=compareTexts(actual,expected,mode),a=c.actual,e=c.expected,max=Math.max(a.length,e.length);let correct=0;for(let i=0;i<max;i++)if(a[i]!==undefined&&a[i]===e[i])correct++;return{correct,incorrect:max-correct,total:max,exact:c.isExact,similarity:c.similarity}}
function handleTypingInput(){const s=state.session;if(!s||s.paused)return;const e=currentEntry(),target=makeTypingTarget(e.term,e.definition),input=$('#typingCapture').value;s.rawChars+=rawCharDelta(s.lastInput,input);s.lastInput=input;const parts=splitTypingInput(input,target.termLength,target.definitionLength),termDone=parts.termInput.length>=target.termLength;renderTypingTerm(parts.termInput,e.term);renderTypingText(parts.definitionInput,e.definition,false,termDone);if(input.length>=target.totalLength){const m=charMetrics(input.slice(0,target.totalLength),target.expected,s.config.matchMode);finalizeTypeLearningEntry({status:m.exact?'completed':'missed',metrics:m})}}
function subjectBucket(entry){const s=state.session;return s.subjectStats[entry.bankId]||(s.subjectStats[entry.bankId]={name:entry.bankName,count:0,correctChars:0,incorrectChars:0,correctItems:0,incorrectItems:0,missed:0})}
function finalizeTypeLearningEntry({status,metrics=null}){const s=state.session,e=currentEntry();if(!s||!e||s.feedback)return;const bucket=subjectBucket(e);bucket.count++;s.processed++;if(metrics){s.correctChars+=metrics.correct;s.incorrectChars+=metrics.incorrect;bucket.correctChars+=metrics.correct;bucket.incorrectChars+=metrics.incorrect}if(status==='completed'){s.completed++;bucket.correctItems++;markOutcome(e,'completed')}else if(status==='missed'){s.missed++;bucket.missed++;bucket.incorrectItems++;markOutcome(e,'missed')}else if(status==='revealed'){s.revealed++;s.missed++;bucket.missed++;bucket.incorrectItems++;markOutcome(e,'revealed')}if(s.config.studyMode==='recall'){s.feedback=true;showRecallFeedback(status);updateProgress();return}advanceEntry()}
function submitRecall(){const s=state.session;if(!s||s.feedback||s.paused)return;const e=currentEntry(),actual=$('#recallInput').value;s.rawChars+=Math.max(0,actual.length-s.lastInput.length);s.lastInput=actual;const m=charMetrics(actual,e.definition,s.config.matchMode);finalizeTypeLearningEntry({status:m.exact?'completed':'missed',metrics:m})}
function tokenizeWords(text){return String(text).trim().split(/\s+/).filter(Boolean)}
function diffWords(actual,expected){const a=tokenizeWords(actual),b=tokenizeWords(expected),dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=a.length-1;i>=0;i--)for(let j=b.length-1;j>=0;j--)dp[i][j]=a[i]===b[j]?1+dp[i+1][j+1]:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,out=[];while(i<a.length||j<b.length){if(i<a.length&&j<b.length&&a[i]===b[j]){out.push(`<span class="same">${esc(b[j])}</span>`);i++;j++}else if(j<b.length&&(i===a.length||dp[i][j+1]>=(dp[i+1]?.[j]??-1))){out.push(`<span class="add">${esc(b[j])}</span>`);j++}else{out.push(`<span class="miss">${esc(a[i])}</span>`);i++}}return out.join(' ')}
function showRecallFeedback(status){const e=currentEntry();$('#correctAnswer').textContent=e.definition;const actual=$('#recallInput').value;$('#diffOutput').innerHTML=actual?diffWords(actual,e.definition):'<span class="add">Answer revealed.</span>';$('#answerPanel').classList.remove('hidden');$('#recallActionRow').classList.add('hidden');$('#nextRecallBtn').focus()}
function revealAnswer(){const s=state.session;if(!s||s.feedback||!s.config.revealAllowed)return;finalizeTypeLearningEntry({status:'revealed'})}
function nextRecall(){if(state.session?.feedback)advanceEntry()}
function answerMcq(originalIndex){const s=state.session,e=currentEntry();if(!s||s.paused||s.feedback||e?.bankType!=='multiple_choice')return;const correct=Number(originalIndex)===e.correctIndex;s.feedback=true;s.processed++;const bucket=subjectBucket(e);bucket.count++;const responseMs=Math.max(0,performance.now()-s.itemStartedAt);s.responseTimes.push(responseMs);if(correct){s.mcqCorrect++;s.completed++;bucket.correctItems++;markOutcome(e,'correct')}else{s.mcqIncorrect++;s.missed++;bucket.missed++;bucket.incorrectItems++;markOutcome(e,'incorrect')}$$('.mcq-choice').forEach(btn=>{btn.disabled=true;const idx=Number(btn.dataset.mcqOriginal);if(idx===e.correctIndex)btn.classList.add('correct');else if(idx===Number(originalIndex))btn.classList.add('wrong')});const panel=$('#mcqExplanationPanel');panel.classList.remove('hidden');const correctText=e.choices[e.correctIndex];$('#mcqCorrectAnswer').textContent=`Correct answer: ${correctText}`;const explanation=$('#mcqExplanation');explanation.textContent=s.config.showExplanations&&e.explanation?e.explanation:'';explanation.classList.toggle('hidden',!(s.config.showExplanations&&e.explanation));$('#mcqNextBtn').classList.remove('hidden');$('#mcqNextBtn').focus();updateProgress()}
function nextMcq(){if(state.session?.feedback)advanceEntry()}
function advanceEntry(){const s=state.session;if(!s)return;s.index++;if(s.index>=s.queue.length){endSession();return}renderSessionEntry()}
function retryCurrentAttempt(){const s=state.session;if(!s||s.ended)return;const order=s.queue.map(e=>`${e.bankId}:${e.entryFingerprint}`);startSession({config:s.config,order})}
function durationMs(config){return 1000*Math.max(1,config.timePreset==='custom'?Number(config.customTime)||60:Number(config.timePreset)||60)}
function updateProgress(){const s=state.session;if(!s)return;if(s.config.sessionType==='time'){const left=Math.max(0,durationMs(s.config)-elapsedMs());$('#progressMain').textContent=`${(left/1000).toFixed(left<10000?1:0)}s`;$('#progressSub').textContent=`${s.processed} ${bankUnitLabel(s.config.bankType,s.processed)}`}else{$('#progressMain').textContent=`${Math.min(s.index+1,s.queue.length)} / ${s.queue.length}`;$('#progressSub').textContent=s.config.bankType==='multiple_choice'?`${s.mcqCorrect} correct • ${s.mcqIncorrect} incorrect`:`${s.completed} correct • ${s.missed} missed`}}
function tickSession(){const s=state.session;if(!s||s.paused||s.ended)return;updateProgress();if(s.config.sessionType==='time'&&elapsedMs()>=durationMs(s.config)){if(currentEntry()&&!s.feedback)s.incomplete++;endSession()}}
function recordSample(){const s=state.session;if(!s||s.paused||s.ended||s.config.bankType==='multiple_choice')return;const stats=computeStats({elapsedMs:elapsedMs(),correctChars:s.correctChars,incorrectChars:s.incorrectChars,rawChars:s.rawChars,samples:s.samples});s.samples.push(stats.wpm);s.accuracySamples.push(stats.accuracy)}
function togglePause(){const s=state.session;if(!s||s.config.sessionType==='time')return;if(!s.paused){s.paused=true;s.pauseStartedAt=performance.now();$('#pausedOverlay').classList.remove('hidden');$('#pauseBtn').textContent='resume'}else{s.pausedMs+=performance.now()-s.pauseStartedAt;s.paused=false;$('#pausedOverlay').classList.add('hidden');$('#pauseBtn').textContent='pause';if(s.config.bankType==='typelearning')(s.config.studyMode==='typing'?$('#typingCapture'):$('#recallInput')).focus()}}
function restartSession(){if(state.session&&confirm('Restart this attempt from the beginning?'))retryCurrentAttempt()}
function newSession(){if(state.session&&!state.session.ended&&state.view==='session'&&!confirm('Leave this attempt and return to setup?'))return;if(state.session){clearInterval(state.session.timerId);clearInterval(state.session.sampleTimer)}state.session=null;switchView('setup');renderSetup()}
function finishStats(s){const coverageAfter=aggregateCoverage(s.banks,state.progress);if(s.config.bankType==='multiple_choice'){const total=s.mcqCorrect+s.mcqIncorrect,accuracy=total?+(s.mcqCorrect/total*100).toFixed(2):0,avg=s.responseTimes.length?s.responseTimes.reduce((a,b)=>a+b,0)/s.responseTimes.length:0;return{bankType:'multiple_choice',score:s.mcqCorrect,totalAnswered:total,accuracy,averageResponseMs:avg,elapsedMs:s.elapsedFinal,completed:s.completed,missed:s.missed,incomplete:s.incomplete,subjectStats:s.subjectStats,coverageBefore:s.coverageBefore,coverageAfter}}const stats=computeStats({elapsedMs:s.elapsedFinal,correctChars:s.correctChars,incorrectChars:s.incorrectChars,rawChars:s.rawChars,samples:s.samples});return{bankType:'typelearning',...stats,correctChars:s.correctChars,incorrectChars:s.incorrectChars,rawChars:s.rawChars,completed:s.completed,missed:s.missed,revealed:s.revealed,incomplete:s.incomplete,processed:s.processed,elapsedMs:s.elapsedFinal,subjectStats:s.subjectStats,samples:s.samples.slice(),accuracySamples:s.accuracySamples.slice(),coverageBefore:s.coverageBefore,coverageAfter}}
function endSession(){const s=state.session;if(!s||s.ended)return;s.ended=true;s.endedAt=performance.now();s.elapsedFinal=elapsedMs();clearInterval(s.timerId);clearInterval(s.sampleTimer);const result=finishStats(s),order=s.queue.map(e=>`${e.bankId}:${e.entryFingerprint}`);state.lastSession={config:structuredClone(s.config),order,result};appendHistory(result,s.config);renderResults(result,s.config);switchView('results')}
function appendHistory(r,config){state.history.unshift({id:makeId('session'),at:new Date().toISOString(),bankType:config.bankType,studyMode:config.bankType==='multiple_choice'?'multiple choice':config.studyMode,sessionType:config.sessionType,length:config.sessionType==='time'?`${config.timePreset==='custom'?config.customTime:config.timePreset}s`:config.definitionPreset,banks:getSelectedBanks(config).map(b=>b.name),wpm:r.wpm??null,accuracy:r.accuracy,score:r.score??null,totalAnswered:r.totalAnswered??null});state.history=state.history.slice(0,50);saveHistory();renderHistory()}
function renderResults(r,config){const isMcq=r.bankType==='multiple_choice';$('#resultHeroLabel1').textContent=isMcq?'score':'wpm';$('#resultHeroLabel2').textContent='accuracy';$('#resultWpm').textContent=isMcq?`${r.score} / ${r.totalAnswered}`:Math.round(r.wpm);$('#resultAccuracy').textContent=`${Number(r.accuracy).toFixed(1)}%`;$('#performanceGraphCard').classList.toggle('hidden',isMcq);const gained=Math.max(0,(r.coverageAfter?.percent||0)-(r.coverageBefore?.percent||0));const items=isMcq?[['correct',r.score],['incorrect',r.totalAnswered-r.score],['avg response',`${(r.averageResponseMs/1000).toFixed(1)}s`],['elapsed',`${(r.elapsedMs/1000).toFixed(1)}s`],['coverage before',`${r.coverageBefore.percent.toFixed(1)}%`],['coverage after',`${r.coverageAfter.percent.toFixed(1)}%`],['coverage gained',`+${gained.toFixed(1)}%`],['incomplete',r.incomplete]]:[['raw wpm',r.rawWpm.toFixed(1)],['consistency',`${r.consistency.toFixed(1)}%`],['correct chars',r.correctChars],['incorrect chars',r.incorrectChars],['completed',r.completed],['missed',r.missed],['revealed',r.revealed],['coverage gained',`+${gained.toFixed(1)}%`],['elapsed',`${(r.elapsedMs/1000).toFixed(1)}s`]];$('#statsGrid').innerHTML=items.map(([k,v])=>`<div class="stat-box"><div class="k">${k}</div><div class="v">${v}</div></div>`).join('');const subjects=Object.values(r.subjectStats);$('#subjectBreakdown').innerHTML=subjects.length?`<table class="subject-table"><thead><tr><th>subject</th><th>items</th><th>accuracy</th><th>missed</th></tr></thead><tbody>${subjects.map(s=>{const a=isMcq?(s.count?s.correctItems/s.count*100:0):((s.correctChars+s.incorrectChars)?s.correctChars/(s.correctChars+s.incorrectChars)*100:0);return`<tr><td>${esc(s.name)}</td><td>${s.count}</td><td>${a.toFixed(1)}%</td><td>${s.missed}</td></tr>`}).join('')}</tbody></table>`:'<span class="subtle">No scored subjects.</span>';$('#resultSessionLabel').textContent=isMcq?'multiple choice':`${config.studyMode} • ${config.matchMode}`;if(!isMcq)requestAnimationFrame(()=>drawPerformanceGraph(r.samples,r.accuracySamples))}
function drawPerformanceGraph(wpm,accuracy){const c=$('#performanceGraph'),ctx=c.getContext('2d'),ratio=devicePixelRatio||1,rect=c.getBoundingClientRect();c.width=Math.max(300,Math.floor(rect.width*ratio));c.height=Math.floor(220*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);const W=rect.width,H=220;ctx.clearRect(0,0,W,H);ctx.strokeStyle='#383a3e';ctx.lineWidth=1;for(let y=30;y<200;y+=40){ctx.beginPath();ctx.moveTo(35,y);ctx.lineTo(W-15,y);ctx.stroke()}const line=(arr,color,maxOverride)=>{if(!arr.length)return;const max=maxOverride||Math.max(10,...arr)*1.15;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();arr.forEach((v,i)=>{const x=35+(W-55)*(arr.length===1?0:i/(arr.length-1)),y=195-(Math.min(v,max)/max)*155;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()};line(wpm,'#e2b714');line(accuracy,'#7aa2a9',100);ctx.fillStyle='#777b84';ctx.font='10px ui-monospace, monospace';ctx.fillText('wpm',38,17);ctx.fillStyle='#e2b714';ctx.fillRect(66,10,15,2);ctx.fillStyle='#777b84';ctx.fillText('accuracy',95,17);ctx.fillStyle='#7aa2a9';ctx.fillRect(151,10,15,2)}
function retrySession(randomize=false){const l=state.lastSession;if(!l)return;startSession(randomize?{config:l.config}:{config:l.config,order:l.order})}

function openDrawer(id){closeDrawers();$('#drawerBackdrop').classList.add('open');const d=$(id);d.classList.add('open');d.setAttribute('aria-hidden','false');if(id==='#banksDrawer')renderBankManager();if(id==='#historyDrawer')renderHistory()}
function closeDrawers(){$('#drawerBackdrop')?.classList.remove('open');$$('.drawer').forEach(d=>{d.classList.remove('open');d.setAttribute('aria-hidden','true')})}
function renderHistory(){const h=$('#historyList');h.innerHTML=state.history.length?state.history.map(x=>`<div class="history-item"><div><div>${esc((x.banks||[]).join(', '))}</div><div class="meta">${new Date(x.at).toLocaleString()} • ${esc(x.bankType==='multiple_choice'?'multiple choice':x.studyMode||'typing')} • ${esc(String(x.length||''))}</div></div><div class="history-score"><div>${x.bankType==='multiple_choice'?`${x.score??0}/${x.totalAnswered??0}`:`${Math.round(x.wpm||0)} wpm`}</div><div class="meta">${Number(x.accuracy||0).toFixed(1)}%</div></div></div>`).join(''):'<span class="subtle">No sessions yet.</span>'}

function bindEvents(){
  document.addEventListener('click',e=>{const setting=e.target.closest('[data-setting] [data-value]');if(setting){const group=setting.closest('[data-setting]'),key=group.dataset.setting,val=setting.dataset.value,prev=state.settings[key];state.settings[key]=val;if(key==='studyMode')updateModeDefault(prev,val);if(key==='bankType'){ensureCompatibleSelection();state.activeBankId=state.settings.singleBankId||compatibleBanks()[0]?.id||state.activeBankId}saveSettings();renderSetup();return}const p=e.target.closest('[data-preset]');if(p){if(p.dataset.preset==='definition')state.settings.definitionPreset=p.dataset.value;else state.settings.timePreset=p.dataset.value;saveSettings();renderSetup();return}const bi=e.target.closest('[data-bank-id]');if(bi){state.activeBankId=bi.dataset.bankId;state.mcqEditorIndex=0;renderBankManager();return}const mcq=e.target.closest('[data-mcq-original]');if(mcq){answerMcq(Number(mcq.dataset.mcqOriginal));return}const remove=e.target.closest('[data-remove-choice]');if(remove){removeMcqChoice(Number(remove.dataset.removeChoice));return}});
  $('#bankSource').onchange=e=>{state.settings.bankSource=e.target.value;saveSettings();renderSetup()};$('#singleBank').onchange=e=>{state.settings.singleBankId=e.target.value;saveSettings();renderSetup()};$('#selectedBanksChecks').onchange=e=>{if(!e.target.dataset.bankCheck)return;const id=e.target.dataset.bankCheck;state.settings.selectedBankIds=e.target.checked?[...new Set([...state.settings.selectedBankIds,id])]:state.settings.selectedBankIds.filter(x=>x!==id);saveSettings();renderSetup()};
  $('#matchMode').onchange=e=>{state.settings.matchMode=e.target.value;saveSettings()};$('#customLength').onchange=e=>{const v=Math.max(1,Number(e.target.value)||1);if(state.settings.sessionType==='definitions')state.settings.customDefinitionCount=v;else state.settings.customTime=v;saveSettings();renderSetup()};['allowCorrections','revealAllowed','shuffleChoices','showExplanations'].forEach(id=>$('#'+id).onchange=e=>{state.settings[id]=e.target.checked;saveSettings()});
  $('#startBtn').onclick=()=>startSession();$('#typingStage').onclick=()=>$('#typingCapture').focus();$('#typingTerm').onclick=()=>$('#typingCapture').focus();$('#typingCapture').oninput=handleTypingInput;$('#typingCapture').onkeydown=e=>{if(!state.session?.config.allowCorrections&&['Backspace','Delete'].includes(e.key))e.preventDefault()};$('#submitRecallBtn').onclick=submitRecall;$('#recallInput').onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();submitRecall()}};$('#nextRecallBtn').onclick=nextRecall;$('#revealBtn').onclick=revealAnswer;$('#recallRetryBtn').onclick=retryCurrentAttempt;$('#typingRetryBtn').onclick=retryCurrentAttempt;$('#mcqNextBtn').onclick=nextMcq;
  $('#pauseBtn').onclick=togglePause;$('#restartBtn').onclick=restartSession;$('#newSessionBtn').onclick=newSession;$('#resultNewBtn').onclick=newSession;$('#retryBtn').onclick=()=>retrySession(false);$('#retryRandomBtn').onclick=()=>retrySession(true);
  $('#banksBtn').onclick=()=>openDrawer('#banksDrawer');$('#manageBanksInline').onclick=()=>openDrawer('#banksDrawer');$('#historyBtn').onclick=()=>openDrawer('#historyDrawer');$('#helpBtn').onclick=()=>openDrawer('#helpDrawer');$('#drawerBackdrop').onclick=closeDrawers;$$('.close-drawer').forEach(b=>b.onclick=closeDrawers);
  $('#newTypeBankBtn').onclick=()=>newBank('typelearning');$('#newMcqBankBtn').onclick=()=>newBank('multiple_choice');$('#saveBankBtn').onclick=saveActiveBank;$('#duplicateBankBtn').onclick=duplicateBank;$('#deleteBankBtn').onclick=deleteBank;$('#exportTxtBtn').onclick=()=>{const b=state.banks.find(x=>x.id===state.activeBankId);if(b)exportBankText(b)};$('#exportJsonBtn').onclick=()=>{const b=state.banks.find(x=>x.id===state.activeBankId);if(b)exportBankJson(b)};$('#exportAllBtn').onclick=exportBackup;$('#importBankBtn').onclick=()=>$('#fileInput').click();$('#importBackupBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{await importFiles([...e.target.files]);e.target.value=''};$('#resetCoverageBtn').onclick=()=>{const b=state.banks.find(x=>x.id===state.activeBankId);if(b&&confirm(`Reset coverage for "${b.name}"?\n\nAll ${b.entries.length} ${bankUnitLabel(b.type,b.entries.length)} will become encounterable again. Lifetime correct/incorrect history will be kept.`))resetBankCoverage(b)};
  $('#mcqQuestionList').onchange=e=>{state.mcqEditorIndex=Math.max(0,Number(e.target.value)||0);const b=state.banks.find(x=>x.id===state.activeBankId);if(b)renderMcqEditor(b)};$('#saveMcqQuestionBtn').onclick=saveMcqQuestion;$('#newMcqQuestionBtn').onclick=newMcqQuestion;$('#duplicateMcqQuestionBtn').onclick=duplicateMcqQuestion;$('#deleteMcqQuestionBtn').onclick=deleteMcqQuestion;$('#addChoiceBtn').onclick=addMcqChoice;
  $('#clearHistoryBtn').onclick=()=>{if(confirm('Clear local session history?')){state.history=[];saveHistory();renderHistory();notify('History cleared.')}};$('#brandHome').onclick=newSession;$('#brandHome').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();newSession()}};
  document.addEventListener('keydown',event=>{if($('.drawer.open')){if(event.key==='Escape')closeDrawers();return}if(state.view==='results'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){if(event.key.toLocaleLowerCase()==='r'){event.preventDefault();retrySession(false)}if(event.key.toLocaleLowerCase()==='n'){event.preventDefault();newSession()}return}if(state.view!=='session')return;const s=state.session;if(s?.config.bankType==='multiple_choice'){if(!s.feedback&&/^[1-6]$/.test(event.key)){const choice=s.currentMcqDisplay?.[Number(event.key)-1];if(choice){event.preventDefault();answerMcq(choice.originalIndex)}}else if(s.feedback&&event.key==='Enter'){event.preventDefault();nextMcq()}else if(event.key==='Escape'){event.preventDefault();restartSession()}}else{if(event.key==='Enter'){event.preventDefault();retryCurrentAttempt()}else if(event.key==='Escape'){event.preventDefault();restartSession()}}});
  window.addEventListener('resize',()=>{if(state.view==='results'&&state.lastSession?.result.bankType==='typelearning')drawPerformanceGraph(state.lastSession.result.samples,state.lastSession.result.accuracySamples)})
}
function init(){loadPersistedState();bindEvents();renderSetup();renderHistory();renderBankManager()}
window.ECEApp={notify,openDrawer,closeDrawers,getActiveBank:()=>{const b=state.banks.find(x=>x.id===state.activeBankId);return b?structuredClone(b):null},getBanks:()=>structuredClone(state.banks),addLocalBank:(raw)=>{const bank=normalizeBank(raw,makeId()),v=validateBank(bank);if(!v.ok)throw new Error(v.errors[0]);bank.id=makeId();bank.name=uniqueBankName(bank.name);mutateBanks(()=>state.banks.push(bank));state.activeBankId=bank.id;state.settings.bankType=bank.type;state.settings.singleBankId=bank.id;state.settings.selectedBankIds=[bank.id];saveSettings();renderSetup();renderBankManager();return structuredClone(bank)},mergeCloudProgress,getCloudProgressPayload,linkActiveBankToCommunity,resetBankCoverageById:(id)=>{const b=state.banks.find(x=>x.id===id);if(b)resetBankCoverage(b)}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
