'use strict';
(function(){
  const cfg=window.ECE_SUPABASE_CONFIG||{},PLACEHOLDER=/YOUR-|YOUR_|example/i;
  const configured=Boolean(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&!PLACEHOLDER.test(cfg.SUPABASE_URL)&&!PLACEHOLDER.test(cfg.SUPABASE_ANON_KEY));
  let client=null,currentUser=null,currentProfile=null,authSubscription=null,searchTimer=null;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  function toast(message){if(window.ECEApp?.notify)window.ECEApp.notify(message);else console.info(message)}
  function text(el,value){if(el)el.textContent=value==null?'':String(value)}function setHidden(el,hidden){if(el)el.classList.toggle('hidden',Boolean(hidden))}
  function cloudReady(){return configured&&Boolean(window.supabase?.createClient)}function requireCloud(){if(!cloudReady())throw new Error('Cloud features are not configured yet. See SETUP.md.');if(!client)throw new Error('Cloud client is not initialized.');return client}function requireUser(){if(!currentUser)throw new Error('Sign in to use this feature.');return currentUser}
  function cleanString(value,max){return String(value??'').trim().slice(0,max)}function typeLabel(type){return type==='multiple_choice'?'MULTIPLE CHOICE':'TYPELEARNING'}function unitLabel(type,count){return type==='multiple_choice'?(count===1?'question':'questions'):(count===1?'definition':'definitions')}
  async function loadProfile(){if(!client||!currentUser){currentProfile=null;return null}const{data,error}=await client.from('profiles').select('id,username,created_at').eq('id',currentUser.id).maybeSingle();if(error)throw error;currentProfile=data||null;return currentProfile}
  async function signUp(email,password,username){const c=requireCloud();email=cleanString(email,320);username=cleanString(username,32);if(!email||!password||username.length<3)throw new Error('Enter a valid email, password, and username of at least 3 characters.');const{data,error}=await c.auth.signUp({email,password,options:{data:{username}}});if(error)throw error;return data}
  async function signIn(email,password){const{data,error}=await requireCloud().auth.signInWithPassword({email:cleanString(email,320),password});if(error)throw error;return data}
  async function signOut(){const{error}=await requireCloud().auth.signOut();if(error)throw error}
  async function updateUsername(username){const c=requireCloud(),user=requireUser();username=cleanString(username,32);if(username.length<3||!/^[A-Za-z0-9_][A-Za-z0-9_.-]*$/.test(username))throw new Error('Username must be 3–32 characters using letters, numbers, underscore, dot, or hyphen.');const{data,error}=await c.from('profiles').update({username}).eq('id',user.id).select('id,username').single();if(error)throw error;currentProfile=data;renderAccountState();return data}
  async function searchBanks(query='',bankType='all'){const c=requireCloud();const bank_type_filter=bankType==='typelearning'||bankType==='multiple_choice'?bankType:'';const{data,error}=await c.rpc('search_public_banks',{search_term:cleanString(query,160),bank_type_filter,limit_count:60});if(error)throw error;return Array.isArray(data)?data:[]}
  async function getBankDetails(bankId){const c=requireCloud();const{data:bank,error:be}=await c.from('banks').select('id,name,subject,description,owner_id,visibility,bank_type,created_at,updated_at').eq('id',bankId).single();if(be)throw be;const{data:owner,error:oe}=await c.from('profiles').select('username').eq('id',bank.owner_id).single();if(oe)throw oe;const{data:rows,error:ee}=await c.from('bank_entries').select('term,definition,question,choices,correct_index,explanation,position').eq('bank_id',bankId).order('position',{ascending:true});if(ee)throw ee;const type=bank.bank_type==='multiple_choice'?'multiple_choice':'typelearning';const entries=(rows||[]).map(row=>type==='multiple_choice'?{question:row.question||'',choices:Array.isArray(row.choices)?row.choices:[],correctIndex:Number(row.correct_index),explanation:row.explanation||''}:{term:row.term||'',definition:row.definition||''});return{...bank,type,uploader_username:owner.username,entries}}
  function entryRows(bankId,localBank){if(localBank.type==='multiple_choice')return localBank.entries.map((e,position)=>({bank_id:bankId,position,term:null,definition:null,question:String(e.question||'').trim(),choices:e.choices.map(c=>String(c||'').trim()),correct_index:Number(e.correctIndex),explanation:String(e.explanation||'').trim()}));return localBank.entries.map((e,position)=>({bank_id:bankId,position,term:String(e.term||'').trim(),definition:String(e.definition||'').trim(),question:null,choices:null,correct_index:null,explanation:''}))}
  async function publishBank(localBank,metadata={}){const c=requireCloud(),user=requireUser();if(!localBank?.name||!Array.isArray(localBank.entries)||!localBank.entries.length)throw new Error('Choose a non-empty local bank first.');const payload={owner_id:user.id,name:cleanString(metadata.name||localBank.name,120),subject:cleanString(metadata.subject,120),description:cleanString(metadata.description,1000),visibility:metadata.visibility==='private'?'private':'public',bank_type:localBank.type==='multiple_choice'?'multiple_choice':'typelearning'};const{data:bank,error:bankError}=await c.from('banks').insert(payload).select('id,name,subject,description,visibility,bank_type').single();if(bankError)throw bankError;const{error:entriesError}=await c.from('bank_entries').insert(entryRows(bank.id,localBank));if(entriesError){await c.from('banks').delete().eq('id',bank.id);throw entriesError}return bank}
  async function updatePublishedBank(bankId,localBank,metadata={}){const c=requireCloud();requireUser();if(!localBank?.entries?.length)throw new Error('The local bank has no entries.');const patch={name:cleanString(metadata.name||localBank.name,120),subject:cleanString(metadata.subject,120),description:cleanString(metadata.description,1000),visibility:metadata.visibility==='private'?'private':'public',bank_type:localBank.type==='multiple_choice'?'multiple_choice':'typelearning'};const{error:be}=await c.from('banks').update(patch).eq('id',bankId);if(be)throw be;const{error:de}=await c.from('bank_entries').delete().eq('bank_id',bankId);if(de)throw de;const{error:ie}=await c.from('bank_entries').insert(entryRows(bankId,localBank));if(ie)throw ie;return true}
  async function getMyUploads(){const c=requireCloud(),user=requireUser();const{data,error}=await c.from('banks').select('id,name,subject,description,visibility,bank_type,created_at,updated_at').eq('owner_id',user.id).order('updated_at',{ascending:false});if(error)throw error;return data||[]}
  async function deletePublishedBank(bankId){requireUser();const{error}=await requireCloud().from('banks').delete().eq('id',bankId);if(error)throw error;return true}
  async function getBankProgress(bankId){if(!currentUser)return[];const{data,error}=await requireCloud().from('user_bank_progress').select('entry_fingerprint,encounter_count,correct_count,incorrect_count,revealed_count,last_encountered_at').eq('bank_id',bankId);if(error)throw error;return data||[]}
  async function recordProgress(bankId,entryFingerprint,delta={}){if(!currentUser||!bankId||!entryFingerprint)return false;const{error}=await requireCloud().rpc('record_bank_progress',{p_bank_id:bankId,p_entry_fingerprint:entryFingerprint,p_encounter_delta:Number(delta.encounterCount||0),p_correct_delta:Number(delta.correctCount||0),p_incorrect_delta:Number(delta.incorrectCount||0),p_revealed_delta:Number(delta.revealedCount||0),p_last_encountered_at:delta.lastEncounteredAt||null});if(error)throw error;return true}
  async function getBankState(bankId){if(!currentUser)return null;const{data,error}=await requireCloud().from('user_bank_state').select('coverage_reset_at').eq('bank_id',bankId).maybeSingle();if(error)throw error;return data||null}
  async function resetBankCoverage(bankId,resetAt=null){if(!currentUser||!bankId)return false;const{error}=await requireCloud().rpc('reset_bank_coverage',{p_bank_id:bankId,p_reset_at:resetAt||new Date().toISOString()});if(error)throw error;return true}
  async function syncBankProgress(bankId){if(!currentUser||!bankId||!window.ECEApp)return false;const[remote,remoteState]=await Promise.all([getBankProgress(bankId),getBankState(bankId)]),merged=window.ECEApp.mergeCloudProgress(bankId,remote,remoteState);const records=Object.entries(merged||{}).filter(([key])=>key!=='__meta').map(([entry_fingerprint,r])=>({entry_fingerprint,encounter_count:Number(r.encounterCount||0),correct_count:Number(r.correctCount||0),incorrect_count:Number(r.incorrectCount||0),revealed_count:Number(r.revealedCount||0),last_encountered_at:r.lastEncounteredAt||null}));if(records.length){const{error}=await requireCloud().rpc('merge_bank_progress_batch',{p_bank_id:bankId,p_records:records});if(error)throw error}const localReset=merged?.__meta?.coverageResetAt;if(localReset){const{error}=await requireCloud().rpc('merge_bank_state',{p_bank_id:bankId,p_coverage_reset_at:localReset});if(error)throw error}return true}
  async function syncAllLocalCommunityProgress(){if(!currentUser||!window.ECEApp?.getBanks)return;const ids=[...new Set(window.ECEApp.getBanks().map(b=>b.community?.bankId).filter(Boolean))];for(const id of ids){try{await syncBankProgress(id)}catch(err){console.error('Progress sync failed',id,err)}}}
  async function saveCommunityBankLocally(bankId){const details=await getBankDetails(bankId);if(!window.ECEApp?.addLocalBank)throw new Error('Local bank integration is unavailable.');const created=window.ECEApp.addLocalBank({name:details.name,type:details.type,entries:details.entries,community:{bankId:details.id,uploader:details.uploader_username,subject:details.subject}});if(currentUser)await syncBankProgress(details.id);return{details,created}}
  function renderCloudStatus(){const status=q('#cloudSetupStatus');if(!status)return;if(cloudReady()){status.className='cloud-status ready';status.textContent='cloud connected'}else{status.className='cloud-status';status.textContent='cloud setup required — see SETUP.md'}}
  function renderAccountState(){renderCloudStatus();setHidden(q('#signedOutAccount'),Boolean(currentUser));setHidden(q('#signedInAccount'),!currentUser);text(q('#accountEmail'),currentUser?.email||'');if(q('#profileUsername'))q('#profileUsername').value=currentProfile?.username||'';if(q('#accountBtn'))q('#accountBtn').textContent=currentProfile?.username?`@${currentProfile.username}`:(currentUser?'account':'sign in')}
  function resultCard(item){const card=document.createElement('article');card.className='community-card';const top=document.createElement('div');top.className='community-card-top';const wrap=document.createElement('div'),title=document.createElement('h3'),badge=document.createElement('span');badge.className=`bank-badge ${item.bank_type==='multiple_choice'?'mcq':''}`;badge.textContent=item.bank_type==='multiple_choice'?'MCQ':'TL';title.textContent=item.name;const meta=document.createElement('div');meta.className='community-meta';meta.textContent=`${item.subject||'Uncategorized'} • ${item.entry_count} ${unitLabel(item.bank_type,item.entry_count)} • uploaded by @${item.uploader_username}`;wrap.append(badge,document.createTextNode(' '),title,meta);const add=document.createElement('button');add.className='primary small-primary';add.textContent='add bank';add.onclick=async()=>{add.disabled=true;try{const{created}=await saveCommunityBankLocally(item.id);toast(`Added "${created.name}" to your local banks.`)}catch(err){toast(err.message)}finally{add.disabled=false}};top.append(wrap,add);card.append(top);if(item.description){const p=document.createElement('p');p.className='community-description';p.textContent=item.description;card.append(p)}return card}
  async function renderSearchResults(query=''){const host=q('#communityResults');if(!host)return;if(!cloudReady()){host.innerHTML='<div class="empty-state">Connect Supabase first to browse community banks.</div>';return}host.innerHTML='<div class="empty-state">searching…</div>';try{const rows=await searchBanks(query,q('#communityTypeFilter')?.value||'all');host.innerHTML='';if(!rows.length){host.innerHTML='<div class="empty-state">No public banks matched your search.</div>';return}rows.forEach(row=>host.append(resultCard(row)))}catch(err){host.innerHTML=`<div class="empty-state">${String(err.message||err)}</div>`}}
  function myUploadCard(item){const row=document.createElement('div');row.className='upload-row';const info=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('div');name.textContent=item.name;meta.className='community-meta';meta.textContent=`${typeLabel(item.bank_type)} • ${item.subject||'Uncategorized'} • ${item.visibility}`;info.append(name,meta);const del=document.createElement('button');del.className='secondary danger';del.textContent='delete';del.onclick=async()=>{if(!confirm(`Delete published bank "${item.name}"?`))return;try{await deletePublishedBank(item.id);await renderMyUploads();await renderSearchResults(q('#communitySearch')?.value||'');toast('Published bank deleted.')}catch(err){toast(err.message)}};row.append(info,del);return row}
  async function renderMyUploads(){const host=q('#myUploads');if(!host)return;if(!currentUser){host.innerHTML='<div class="empty-state">Sign in to see your uploads.</div>';return}try{const rows=await getMyUploads();host.innerHTML='';if(!rows.length){host.innerHTML='<div class="empty-state">You have not published any banks yet.</div>';return}rows.forEach(r=>host.append(myUploadCard(r)))}catch(err){host.innerHTML=`<div class="empty-state">${String(err.message||err)}</div>`}}
  async function publishActiveLocalBank(){if(!currentUser){toast('Sign in before publishing a bank.');window.ECEApp?.openDrawer?.('#accountDrawer');return}const bank=window.ECEApp?.getActiveBank?.();if(!bank){toast('Choose a local bank in Bank Manager first.');return}const subject=q('#cloudPublishSubject')?.value||'',description=q('#cloudPublishDescription')?.value||'',visibility=q('#cloudPublishVisibility')?.value||'public',button=q('#publishCloudBtn');if(button)button.disabled=true;try{const published=await publishBank(bank,{subject,description,visibility});window.ECEApp?.linkActiveBankToCommunity?.(published.id,currentProfile?.username||'',subject);await syncBankProgress(published.id);toast(`Published "${published.name}" as ${typeLabel(published.bank_type)}.`);await renderMyUploads();await renderSearchResults(q('#communitySearch')?.value||'')}catch(err){toast(err.message)}finally{if(button)button.disabled=false}}
  async function refreshAuthState(){if(!client)return;const{data,error}=await client.auth.getSession();if(error)throw error;currentUser=data.session?.user||null;await loadProfile();renderAccountState();if(currentUser){await renderMyUploads();await syncAllLocalCommunityProgress()}}
  function bindUI(){q('#communityBtn')?.addEventListener('click',()=>{window.ECEApp?.openDrawer?.('#communityDrawer');renderSearchResults(q('#communitySearch')?.value||'')});q('#accountBtn')?.addEventListener('click',()=>{window.ECEApp?.openDrawer?.('#accountDrawer');renderAccountState();if(currentUser)renderMyUploads()});q('#communitySearch')?.addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>renderSearchResults(e.target.value),220)});q('#communityTypeFilter')?.addEventListener('change',()=>renderSearchResults(q('#communitySearch')?.value||''));q('#loginBtn')?.addEventListener('click',async()=>{try{await signIn(q('#authEmail').value,q('#authPassword').value);toast('Signed in.')}catch(err){toast(err.message)}});q('#signupBtn')?.addEventListener('click',async()=>{try{const data=await signUp(q('#authEmail').value,q('#authPassword').value,q('#authUsername').value);toast(data.session?'Account created and signed in.':'Account created. Check your email to confirm it.')}catch(err){toast(err.message)}});q('#logoutBtn')?.addEventListener('click',async()=>{try{await signOut();toast('Signed out.')}catch(err){toast(err.message)}});q('#saveUsernameBtn')?.addEventListener('click',async()=>{try{await updateUsername(q('#profileUsername').value);toast('Username updated.')}catch(err){toast(err.message)}});q('#publishCloudBtn')?.addEventListener('click',publishActiveLocalBank);q('#refreshUploadsBtn')?.addEventListener('click',renderMyUploads);qa('[data-open-community]').forEach(el=>el.addEventListener('click',()=>{window.ECEApp?.openDrawer?.('#communityDrawer');renderSearchResults('')}));qa('[data-open-account]').forEach(el=>el.addEventListener('click',()=>{window.ECEApp?.openDrawer?.('#accountDrawer');renderAccountState();if(currentUser)renderMyUploads()}))}
  async function init(){bindUI();renderCloudStatus();if(!cloudReady()){renderAccountState();renderSearchResults('');return false}client=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});await refreshAuthState();const{data}=client.auth.onAuthStateChange(async(_event,session)=>{currentUser=session?.user||null;try{await loadProfile();renderAccountState();await renderMyUploads();if(currentUser)await syncAllLocalCommunityProgress()}catch(err){console.error(err)}});authSubscription=data?.subscription||null;await renderSearchResults('');return true}
  window.ECECloud={init,signUp,signIn,signOut,updateUsername,searchBanks,getBankDetails,publishBank,updatePublishedBank,getMyUploads,deletePublishedBank,saveCommunityBankLocally,getBankProgress,getBankState,recordProgress,resetBankCoverage,syncBankProgress,isConfigured:()=>cloudReady(),getCurrentUser:()=>currentUser,getCurrentProfile:()=>currentProfile,destroy:()=>authSubscription?.unsubscribe?.()};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init().catch(console.error));else init().catch(console.error);
})();
